.github/pull_request_template.md

This template helps not to forget to do something when submitting a PR.

Added a PR checklist template

---

README.md

Link to solid-client library

---

__tests__/ClientAuthn.spec.ts
__tests__/dependencies.node.spec.ts
__tests__/dependencies.spec.ts
__tests__/localStorage/StorageUtility.spec.ts
docs/browser.md
examples/single/bundle/src/App.js
examples/single/native/android/app/_BUCK
examples/single/native/android/app/build.gradle
examples/single/native/android/app/src/main/AndroidManifest.xml
examples/single/native/android/app/src/main/java/com/solidauthfetcherreactnativedemo/MainActivity.java
examples/single/native/android/app/src/main/java/com/solidauthfetcherreactnativedemo/MainApplication.java
examples/single/native/android/app/src/main/res/values/strings.xml
examples/single/native/android/settings.gradle
examples/single/native/app.json
examples/single/native/ios/Podfile
examples/single/native/ios/solidAuthFetcherReactNativeDemo/AppDelegate.m
examples/single/native/ios/solidAuthFetcherReactNativeDemo/Base.lproj/LaunchScreen.xib
examples/single/native/ios/solidAuthFetcherReactNativeDemo/Info.plist
examples/single/native/ios/solidAuthFetcherReactNativeDemoTests/solidAuthFetcherReactNativeDemoTests.m
examples/single/script/index.html
src/ClientAuthentication.ts
src/Session.ts
src/SessionManager.ts
src/dependencies.ts
src/index.browser.ts
src/index.ts
src/storage/StorageUtility.ts
webpack.browser.js

Some internal variables still use the abbreviation.

Changed authn into authentication in function and class names

---

src/ClientAuthentication.ts
src/Session.ts

This PR reintroduces fixes from #245 which were accidentally rebased out of existence.

Use properties instead of class methods for session

---

src/Session.ts

This PR fixes a login emitter bug.

Await login before emitting

---

.github/pull_request_template.md
.github/workflows/cd-release.yml

This introduces a release CD pipeline, triggered when a tag is pushed. The release checklist is added to the PR checklist.

Set up CD for release publication

---

README.md

See https://github.com/inrupt/solid-client-js/commit/0e30dd74297a2f5725fc6708fcf36ab87f5a3177

Align with changes in solid-client-js README

---

README.md

Added a note about NSS compatibility

---

.github/workflows/cd-release.yml

Instead of looking into the `package.json` based on the tag, lerna was trying to do something smart, but which doesn't match our pipeline. This flag enforces it to behave the way we expect.

Fix lerna publication to NPM

---

packages/browser/docs/api/redirects.txt

Add redirects for the renamed API docs.

Add redirects for api docs

---

vercel.json

Disable Vercel commenting on each Pull Request

---

package.json
packages/browser/package.json
packages/core/docs/api/Makefile
packages/core/docs/api/README.md
packages/core/docs/api/_static/css/inrupt.css
packages/core/docs/api/_templates/docs-navbar.html
packages/core/docs/api/_templates/docs-sidebar.html
packages/core/docs/api/_templates/edit_this_page.html
packages/core/docs/api/_templates/footer.html
packages/core/docs/api/_templates/index.rst
packages/core/docs/api/_templates/layout.html
packages/core/docs/api/conf.py
packages/core/docs/api/requirements.txt
packages/core/docs/api/source/index.rst
packages/core/docs/api/themes/inrupt/theme.conf
packages/core/package.json
tsconfig.build.json

**Note:** This build on #314, so best to merge that before reviewing this.
This adds the setup for the API docs website for solid-client-authn-core.

Also generate API docs for solid-client-authn-core

---

packages/browser/__tests__/login/oidc/ClientRegistrar.spec.ts
packages/oidc-dpop-client-browser/src/dcr/clientRegistrar.spec.ts
packages/oidc-dpop-client-browser/src/dcr/clientRegistrar.ts

The response to the client registration request is checked for a client_id, and the returned redirect_uris are matched against the values that were provided. These are the only mandatory behaviours.

Validate client registration response

---

.github/ISSUE_TEMPLATE/bug_report.md

This will also give us information about which versions of our
packages they are using, in addition to their OS and browsers.

Ask bug reporters to run npx envinfo

---

packages/browser/__tests__/login/oidc/ClientRegistrar.spec.ts
packages/browser/package-lock.json
packages/oidc-dpop-client-browser/src/dcr/clientRegistrar.spec.ts
packages/oidc-dpop-client-browser/src/dcr/clientRegistrar.ts

This commit introduces cleaner error management when client registration fails.

Failed registration response processing

---

packages/browser/docs/api/conf.py
packages/browser/docs/api/requirements.txt
packages/core/docs/api/conf.py
packages/core/docs/api/requirements.txt

Docs changes: To use the latest pydata-sphinx-theme, explicitly include the sidebar nav and remove pinned version in requirements.

DOCS-199: changes for updated theme 

---

.github/workflows/cd-preview.yml

Motivated by https://github.com/inrupt/solid-client-js/pull/556

Upgrade GH action env variable management

---

packages/browser/__tests__/ClientAuthentication.spec.ts
packages/browser/__tests__/authenticatedFetch/fetchFactory.spec.ts
packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts
packages/browser/__tests__/login/oidc/redirectHandler/FallbackRedirectHandler.spec.ts
packages/browser/__tests__/login/oidc/redirectHandler/ImplicitRedirectHandler.spec.ts
packages/browser/__tests__/util/Fetcher.spec.ts
packages/browser/package-lock.json
packages/browser/package.json
packages/browser/src/authenticatedFetch/fetchFactory.ts
packages/browser/src/sessionInfo/SessionInfoManager.ts
packages/browser/src/util/Fetcher.ts
packages/core/package-lock.json
packages/core/package.json

Fixes #180 .
Since the package does not intend to be isomorphic, it can make the assumption that the fetch should default to the window's.

Removed dependency on cross-fetch

---

packages/browser/examples/single/bundle/package.json
packages/browser/examples/single/bundle/src/App.js

This updates the single/bundle app in order to improve React practices. It also adds a logout button.
This sample app has a different purpose than the demoClient app: the latter has a richer UI and more features, while the former basically provides code snippets serving as documentation.

Simplified the sample app

---

packages/browser/__tests__/authenticatedFetch/fetchFactory.spec.ts
packages/browser/__tests__/login/oidc/TokenRequester.spec.ts
packages/browser/src/authenticatedFetch/fetchFactory.ts
packages/browser/src/login/oidc/TokenRequester.ts
packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts
packages/browser/src/login/oidc/redirectHandler/ImplicitRedirectHandler.ts
packages/oidc/src/dpop/tokenExchange.ts

Reapplies https://github.com/inrupt/solid-client-authn-js/pull/446 on top of `master`

add first phase of refresh token handling

---

CHANGELOG.md
lerna.json
packages/browser/package-lock.json
packages/browser/package.json
packages/core/package-lock.json
packages/core/package.json
packages/oidc/package-lock.json
packages/oidc/package.json

This PR bumps the version to 0.3.0.

Release 0.3.0

---

packages/browser/examples/single/script/index.html

This simplify example code for it to be reused in the documentation.
- Removed `URL` objects from interfaces
- Removed call to `...WithResolvedDependencies`

Refactored script example

---

packages/browser/docs/api/_templates/layout.html
packages/core/docs/api/_templates/layout.html

Update docs' Matomo Tracking code

DOCS-208: update matomo tracking code

---

.github/dependabot.yml
packages/node/.eslintrc.js
packages/node/.npmignore
packages/node/docs/api/Makefile
packages/node/docs/api/README.md
packages/node/docs/api/_static/css/inrupt.css
packages/node/docs/api/_templates/docs-navbar.html
packages/node/docs/api/_templates/docs-sidebar.html
packages/node/docs/api/_templates/edit_this_page.html
packages/node/docs/api/_templates/footer.html
packages/node/docs/api/_templates/index.rst
packages/node/docs/api/_templates/layout.html
packages/node/docs/api/conf.py
packages/node/docs/api/requirements.txt
packages/node/docs/api/themes/inrupt/theme.conf
packages/node/jest.config.js
packages/node/package-lock.json
packages/node/package.json
packages/node/src/index.ts
packages/node/tsconfig.eslint.json
packages/node/tsconfig.json

This sets up:
- Tests
- Docs
- Linting
for the node module of solid-client-authn.
Note: This reapplies the node setup commits, lost when merging the shared ESlint configuration.

Setup node project

---

packages/node/package-lock.json
packages/node/package.json
packages/node/src/login/oidc/IssuerConfigFetcher.spec.ts
packages/node/src/login/oidc/IssuerConfigFetcher.ts

OIDC issuer config is now fetched using `openid-client`, and it is only validated in our library.

Reimplemented OIDC issuer config

---

packages/node/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts
packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts

The OAuth state must be passed explicitly, and the challenge generation algorithm must be specified.

Fixed parameters passed to openid-client callback

---

CHANGELOG.md
packages/browser/__tests__/ClientAuthentication.spec.ts
packages/browser/__tests__/Session.spec.ts
packages/browser/examples/single/script/index.html
packages/browser/src/ClientAuthentication.ts

remove query params from URL after redirect

---

packages/browser/examples/demoClientApp/src/DemoClientApp.js
packages/browser/package-lock.json
packages/node/example/demoClientApp/src/index.html
packages/node/example/demoClientApp/src/index.js

Chore - just tidying up UI to report resource details in a scrollable text area, and fixed up status messages.

tidied up UI now that login working

---

CHANGELOG.md
lerna.json
packages/browser/package-lock.json
packages/browser/package.json
packages/core/package-lock.json
packages/core/package.json
packages/node/package-lock.json
packages/node/package.json
packages/oidc/package-lock.json
packages/oidc/package.json

This PR bumps the version to 1.2.1.

1.2.1 release

---

README.md
packages/browser/README.md
packages/node/README.md

Initialise a proper readme for SCAN

---

e2e/browser/README.md
e2e/browser/page-models/LoginPage.ts
e2e/browser/testSuiteRunner.test.ts

Replay of d02a42a3e937b774287df00a6ba47c34da15ac3b without the
package-lock updates.

Rephrased e2e test description with debug hints

---

CHANGELOG.md
packages/browser/__tests__/Session.spec.ts
packages/browser/src/ClientAuthentication.ts
packages/browser/src/Session.ts
packages/browser/src/sessionInfo/SessionInfoManager.ts

Fix unauthenticated fetch bug

---

package.json

Compare https://solid-client-authn-js-efiklfo23.vercel.app/ and https://solid-client-authn-js-qy06t72cc.vercel.app/.

Also link to the Node docs on the preview site

---

CHANGELOG.md
packages/browser/__tests__/login/oidc/ClientRegistrar.spec.ts
packages/oidc/src/dcr/clientRegistrar.spec.ts
packages/oidc/src/dcr/clientRegistrar.ts

This PR fixes bug #1101 by re-applying https://github.com/inrupt/solid-client-authn-js/pull/1102. Thanks for reporting, and then fixing this :).

Fix: remove PKCE-related information from DCR

---

CHANGELOG.md
lerna.json
packages/browser/package-lock.json
packages/browser/package.json
packages/core/package-lock.json
packages/core/package.json
packages/node/package-lock.json
packages/node/package.json
packages/oidc/package-lock.json
packages/oidc/package.json

This PR bumps the version to 1.7.1.

Release v1.7.1

---

packages/browser/examples/single/bundle/src/App.js

It is now https://broker.pod.inrupt.com, instead of dev-ess. This also
adds a clientName parameter to login.

Changed thedemo app's default IdP

---

package-lock.json

This commit is the result of running `npm audit fix` when NPM detected a security issue.

Updated dependencies to fix security issue

---

CHANGELOG.md
lerna.json
packages/browser/package-lock.json
packages/browser/package.json
packages/core/package-lock.json
packages/core/package.json
packages/node/package-lock.json
packages/node/package.json
packages/oidc/package-lock.json
packages/oidc/package.json

This PR bumps the version to 1.8.1.

Release 1.8.1

---

.eslintrc.js
jest.e2e.config.js
packages/node/jest.config.js
packages/node/jest.e2e.config.js
packages/node/package-lock.json
packages/node/package.json
packages/node/src/authenticatedFetch/fetchFactory.spec.ts
packages/node/src/authenticatedFetch/fetchFactory.ts
packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.ts
packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts
packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts
packages/node/src/login/oidc/refresh/TokenRefresher.spec.ts
packages/node/src/login/oidc/refresh/TokenRefresher.ts

This PR simply rebases #796 on top of `main`. Since there are no build/test errors, I assume that means all use of Jose is now covered.

Upgrade jose to v3

---

packages/browser/__tests__/Session.spec.ts
packages/browser/src/Session.ts

After completing silent authentication in an iframe, the `info` property on the Session wasn't updated. It is now, and I've extracted the code for doing so, which is shared with `handleIncomingRedirect`, into the `setSessionInfo` method, primarily so that there's a single place to change to make sure the session is silently refreshed rather than terminated when it expires.

Set sessionInfo after completing silent auth

---

CHANGELOG.md
lerna.json
packages/browser/package-lock.json
packages/browser/package.json
packages/core/package-lock.json
packages/core/package.json
packages/node/package-lock.json
packages/node/package.json
packages/oidc/package-lock.json
packages/oidc/package.json

This PR bumps the version to 1.8.2.

Release v1.8.2

---

packages/node/src/dependencies.ts

Just minor readability improvements, based on Ruben's comments.

Minor readability improvements to ClientAuthentication creation

---

CHANGELOG.md
packages/browser/src/ClientAuthentication.ts

Bind fetch to window

---

CHANGELOG.md
lerna.json
packages/browser/package-lock.json
packages/browser/package.json
packages/core/package-lock.json
packages/core/package.json
packages/node/package-lock.json
packages/node/package.json
packages/oidc/package-lock.json
packages/oidc/package.json

This PR bumps the version to 1.9.1.

Release v1.9.1

---

packages/browser/__tests__/ClientAuthentication.spec.ts
packages/browser/__tests__/Session.spec.ts
packages/browser/__tests__/login/oidc/redirectHandler/ErrorOidcHandler.spec.ts
packages/browser/examples/single/bundle/src/App.js
packages/browser/src/ClientAuthentication.ts
packages/browser/src/Session.ts
packages/browser/src/dependencies.ts
packages/browser/src/login/oidc/redirectHandler/AggregateRedirectHandler.ts
packages/browser/src/login/oidc/redirectHandler/ErrorOidcHandler.ts
packages/core/src/index.ts
packages/core/src/login/ILoginOptions.ts
packages/core/src/login/oidc/redirectHandler/IRedirectHandler.ts

Handle login error

---

CHANGELOG.md

Fixing date for 1.10.1 in the changelog

Fixing month number for 1.10.1

---

package-lock.json

Ran npm audit fix to fix https://npmjs.com/advisories/1773

Fixed security advisory

---

.github/workflows/e2e-browser.yml
.github/workflows/e2e-node.yml
e2e/node/server/e2e-app-test.spec.ts

Stop testing against ESS 2.1 in CI

Remove ESS Dev-2-1 environment

---

CHANGELOG.md
e2e/browser/solid-client-authn-browser/test-app/package.json
e2e/browser/solid-ui-react/test-app/package.json
lerna.json
package-lock.json
packages/browser/examples/single/bundle/package.json
packages/browser/examples/single/script/package.json
packages/browser/package.json
packages/core/package.json
packages/core/src/login/ILoginOptions.ts
packages/core/src/sessionInfo/ISessionInfo.ts
packages/node/examples/authenticated-script/package.json
packages/node/examples/demoClientApp/package.json
packages/node/examples/multiSession/package.json
packages/node/package.json
packages/oidc-browser/package.json

This PR bumps the version to 2.2.0.
1. Look at the [CHANGELOG.md](../CHANGELOG.md) to determine whether the release should be a major, minor, or patch release. Coordinate with the team to ensure the next version is agreed upon.
2. Run `npm run lerna-version -- <major|minor|patch>` with the decided on version.
3. Update the `CHANGELOG.md` to release the latest the version, and set the release date.
4. Commit the changes on a `release/vX.Y.Z` branch
5. Push to GitHub, create a PR, and merge once CI passes.
6. Create a release on GitHub for the new version, using a combination of the release notes from the `CHANGELOG.md` and the automatically generated changes.

Release v2.2.0

---

CHANGELOG.md
e2e/browser/solid-client-authn-browser/test-app/package.json
e2e/browser/solid-ui-react/test-app/package.json
lerna.json
package-lock.json
packages/browser/examples/single/bundle/package.json
packages/browser/examples/single/script/package.json
packages/browser/package.json
packages/core/package.json
packages/node/examples/authenticated-script/package.json
packages/node/examples/demoClientApp/package.json
packages/node/examples/multiSession/package.json
packages/node/package.json
packages/oidc-browser/package.json

This PR bumps the version to 2.2.1.
1. Look at the [CHANGELOG.md](../CHANGELOG.md) to determine whether the release should be a major, minor, or patch release. Coordinate with the team to ensure the next version is agreed upon.
2. Run `npm run lerna-version -- <major|minor|patch>` with the decided on version.
3. Update the `CHANGELOG.md` to release the latest the version, and set the release date.
4. Commit the changes on a `release/vX.Y.Z` branch
5. Push to GitHub, create a PR, and merge once CI passes.
6. Create a release on GitHub for the new version, using a combination of the release notes from the `CHANGELOG.md` and the automatically generated changes.

Release v2.2.1

---

CHANGELOG.md
e2e/browser/solid-client-authn-browser/test-app/package.json
e2e/browser/solid-ui-react/test-app/package.json
lerna.json
package-lock.json
packages/browser/examples/single/bundle/package.json
packages/browser/examples/single/script/package.json
packages/browser/package.json
packages/core/package.json
packages/node/examples/authenticated-script/package.json
packages/node/examples/demoClientApp/package.json
packages/node/examples/multiSession/package.json
packages/node/package.json
packages/oidc-browser/package.json

This PR bumps the version to v2.2.3.
1. Look at the [CHANGELOG.md](../CHANGELOG.md) to determine whether the release should be a major, minor, or patch release. Coordinate with the team to ensure the next version is agreed upon.
2. Run `npm run lerna-version -- <major|minor|patch>` with the decided on version.
3. Update the `CHANGELOG.md` to release the latest the version, and set the release date.
4. Commit the changes on a `release/vX.Y.Z` branch
5. Push to GitHub, create a PR, and merge once CI passes.
6. Create a release on GitHub for the new version, using a combination of the release notes from the `CHANGELOG.md` and the automatically generated changes.

Release v2.2.3

---

CHANGELOG.md
e2e/browser/solid-client-authn-browser/test-app/package.json
e2e/browser/solid-ui-react/test-app/package.json
lerna.json
package-lock.json
packages/browser/examples/single/bundle/package.json
packages/browser/examples/single/script/package.json
packages/browser/package.json
packages/core/package.json
packages/node/examples/authenticated-script/package.json
packages/node/examples/demoClientApp/package.json
packages/node/examples/multiSession/package.json
packages/node/package.json
packages/oidc-browser/package.json

This PR bumps the version to v2.2.4.
1. Look at the [CHANGELOG.md](../CHANGELOG.md) to determine whether the release should be a major, minor, or patch release. Coordinate with the team to ensure the next version is agreed upon.
2. Run `npm run lerna-version -- <major|minor|patch>` with the decided on version.
3. Update the `CHANGELOG.md` to release the latest the version, and set the release date.
4. Commit the changes on a `release/vX.Y.Z` branch
5. Push to GitHub, create a PR, and merge once CI passes.
6. Create a release on GitHub for the new version, using a combination of the release notes from the `CHANGELOG.md` and the automatically generated changes.

Release v2.2.4

---

e2e/browser/solid-client-authn-browser/test-app/package.json
package-lock.json
packages/browser/package.json
packages/node/package.json
packages/node/src/login/oidc/__mocks__/ClientRegistrar.ts

Updates @types/node from 22.10.1 to 22.10.7 and fixes a test where a type was not specific enough

Update @types/node and fix test

---

CHANGELOG.md
e2e/browser/solid-client-authn-browser/test/fixtures.ts
e2e/node/script/e2e-test.spec.ts
e2e/node/server/e2e-app-test.spec.ts
e2e/node/server/e2e-browser-script.spec.ts
e2e/node/server/express.ts
packages/core/src/SessionEventListener.ts
packages/core/src/authenticatedFetch/fetchFactory.spec.ts
packages/core/src/authenticatedFetch/fetchFactory.ts
packages/core/src/constant.ts
packages/core/src/index.ts
packages/core/src/logout/__mocks__/LogoutHandler.ts
packages/node/src/Session.spec.ts
packages/node/src/index.ts
packages/node/src/login/oidc/incomingRedirectHandler/AuthCodeRedirectHandler.spec.ts
packages/node/src/login/oidc/incomingRedirectHandler/AuthCodeRedirectHandler.ts
packages/node/src/login/oidc/oidcHandlers/ClientCredentialsOidcHandler.spec.ts
packages/node/src/login/oidc/oidcHandlers/ClientCredentialsOidcHandler.ts
packages/node/src/login/oidc/refresh/TokenRefresher.spec.ts
packages/node/src/login/oidc/refresh/TokenRefresher.ts

SDK-3405: Emit event when new tokens are received

---

CHANGELOG.md
e2e/node/server/e2e-app-test.spec.ts
e2e/node/server/express.ts
packages/browser/src/login/oidc/incomingRedirectHandler/AuthCodeRedirectHandler.ts
packages/core/src/SessionEventListener.ts
packages/core/src/authenticatedFetch/fetchFactory.spec.ts
packages/core/src/authenticatedFetch/fetchFactory.ts
packages/core/src/sessionInfo/ISessionInfoManager.ts
packages/core/src/sessionInfo/SessionInfoManager.ts
packages/node/src/ClientAuthentication.spec.ts
packages/node/src/ClientAuthentication.ts
packages/node/src/Session.fromTokens.spec.ts
packages/node/src/Session.spec.ts
packages/node/src/Session.ts
packages/node/src/login/oidc/incomingRedirectHandler/AuthCodeRedirectHandler.ts
packages/node/src/login/oidc/oidcHandlers/ClientCredentialsOidcHandler.ts
packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.spec.ts
packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.ts
packages/node/src/login/oidc/refresh/TokenRefresher.ts
packages/node/src/multiSession.ts
packages/node/src/sessionInfo/SessionInfoManager.spec.ts
packages/node/src/sessionInfo/SessionInfoManager.ts

SDK-3406: Add support for creating a session by injecting tokens

---

packages/node/examples/server/.env.example
packages/node/examples/server/src/serverSideApp.mjs

This updates the NodeJS server example to show the latest recommended way to log out.

Update nodejs logout example
