inrupt/solid-client-authn-js

__tests__/authenticatedFetch/dpop/DpopAuthenticatedFetcher.spec.ts, src/authenticatedFetch/dpop/DpopAuthenticatedFetcher.ts
Resolves #88
It seems that an object implementing correctly the `Headers` interface is not processed correctly by `node-fetch`, pulled in by `cross-fetch`. I'll develop a minimal example to verify that this diagnosis is correct, and if so create an appropriate issue in the relevant repo.
=> The `Headers` object is now flattened before fetch

src/authenticatedFetch/dpop/DpopAuthenticatedFetcher.ts
Following a conversation we had around this exact topic in an NSS PR, I realized that the code I just wrote to fix the Headers issue used `lib.dom.d.ts:Headers` as a class, which is incorrect. The weird thing is that this line is covered by unit tests that did not pick up the issue, neither did the downstream libraries using the code (e.g. `LDflex-Comunica`). It's only when writing a super-simple code snippet (see below) for test purpose that this blew up:
```javascript
const auth = require('@inrupt/solid-auth-fetcher')
auth.fetch("http://some.iri/")
.then(response => response.text())
.then(data => console.log(data));
```
=> Replaced Headers type by NodeHeaders class for instantiation

.github/workflows/whitesource.yml
There is a bug in Whitesource that makes it impractical for CI status checks. However, this change still runs a Whitesource scan on push to master, so that our dashboard stays in sync with the state of the repository. It won't affect the CI pipeline, and might introduce false positives that we can manually dismiss, but it still provides some feedback on security issues.
=> Disabled Whitesource CI status check

package.json, webpack.browser.js, webpack.common.js
Updates the libraryTarget to export a commonjs module, which plays nicely with nodejs. However, this will _not_ export a global variable like it currently does - which means you can't just drop the compiled javascript on a page (like the first example on the README.) Two questions:
* Is exporting a global variable useful, or can we assume any user of SAF is using a bundler like webpack?
* If so, we can create a "dist/browser.js" file that imports "dist/index.js" and sets `global.solidAuthFetcher`.
=> Fix webpack export

package.json
The browser field hints to bundlers like webpack to use that file for
browser packages; as this is the npm package, it's unnecessary and
causes bundled code to act differently from node.js code.
Users who want to use the browser bundle can still build the project and
drop browserDist into their projects.
=> Remove browser from package.json

.github/workflows/cd-preview.yml
This PR fixes a undesired behaviour by creating a large number of preview releases due to dependabot PRs.
=> Exclude dependabot branches from the preview-app releases

__tests__/authenticatedFetch/headers/HeadersUtils.spec.ts, src/authenticatedFetch/dpop/DpopAuthenticatedFetcher.ts, src/authenticatedFetch/headers/HeadersUtils.ts, src/authenticatedFetch/unauthenticated/UnauthenticatedFetcher.ts
The previous workaround was unnecessarily convoluted, and a simpler, more standard approach is supported. However, there is still a conflict between the `lib.dom.d.ts` Headers type and the reference https://fetch.spec.whatwg.org/#headers-class. An issue will be opened to track this.
This PR contributes to fixing bug #176.
=> Clean the LDflex workaround up

__tests__/util/Fetcher.spec.ts, src/util/Fetcher.ts
If a browser fetch implementation is available, then it is used instead of `cross-fetch`. This is because cross-fetch uses a polyfill for fetch, which is incomplete and lacks some standard behaviour that is required in some of our use cases, such as reading responses as streams for LDflex.
This PR contributes to fixing bug #173. However, the problem persists in a `Node` environment.
=> Defaults to a browser fetch instead of `cross-fetch`

README.md
This PR duplicates the changes in https://github.com/inrupt/solid-client-authn/pull/249. It looks like Travis doesn't work well with forks/inline edits, I'll create a ticket to fix this in the future.
=> Aligns README with other solid-client libraries

CHANGELOG.MD, __tests__/authenticatedFetch/bearer/BearerAuthenticatedFetcher.spec.ts, src/authenticatedFetch/bearer/BearerAuthenticatedFetcher.ts
This adds a fetcher issuing requests authenticated using a bearer token. Note that requesting said bearer token, or appropriately selecting the fetcher, is outside of the scope of this PR.
=> Implement bearer token authenticated fetcher

examples/single/bundle/src/App.js, src/dependencies.ts, src/login/oidc/ClientRegistrar.ts, src/login/oidc/oidcHandlers/LegacyImplicitFlowOidcHandler.ts
For some reason, dynamic client registration information isn't persisted when interacting with NSS if stored in secure storage. If stored in insecure storage though, it works and prevents us from having to deal with the legacy token.
=> Fix client registration issue in the auth code flow on NSS

__tests__/authenticatedFetch/bearer/BearerAuthenticatedFetcher.spec.ts, __tests__/authenticatedFetch/dpop/DpopAuthenticatedFetcher.spec.ts, __tests__/authenticatedFetch/unauthenticated/UnautenticatedFetcher.spec.ts, __tests__/login/oidc/ClientRegistrar.spec.ts, __tests__/login/oidc/IssuerConfigFetcher.spec.ts, __tests__/login/oidc/TokenRequester.spec.ts, __tests__/logout/GeneralLogoutHandler.spec.ts, __tests__/sessionInfo/SessionInfoManager.spec.ts, src/logout/GeneralLogoutHandler.ts, src/storage/__mocks__/StorageUtility.ts
Since pieces of information are stored in both local and in-memory storage, both should be cleared on logout. This enables to log in a different IdP after logging out.
Note that the bug preventing to log in the same IdP with a different account is not in the scope of this PR.
=> Clears both local and in-memory storage on logout

apidocs/Makefile, apidocs/_templates/docs-sidebar.html, apidocs/conf.py, apidocs/source/index.rst, docs/Makefile, docs/conf.py, docs/source/api.rst, docs/source/includes/table-issues-help.rst, docs/source/index.rst, docs/source/issues-help.rst
Minor fixes to configuration and makefile to build the docs:
- Update API docs conf.py - API docs don't need tabs/copy button extensions (and isn't part of the requirements.txt)
- Update API docs Makefile - when copying to  build directory, update the api docs structure
- Update API docs Makefile - clean .md files in all api directories, not just modules
- Update reference docs Makefile - missing the sphinx-builder line for the html target
=> Docs: Update to build

packages/browser/package.json
Update build-api-docs definition: Specify `--readme none` for so that typedoc generates a README.md for the API files instead of copying the packages/browser/README.md file.
=> build-api-docs: --readme none

CHANGELOG.md, packages/browser/__tests__/ClientAuthn.spec.ts, packages/browser/__tests__/login/oidc/OidcLoginHandler.spec.ts, packages/browser/__tests__/logout/GeneralLogoutHandler.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/login/oidc/OidcLoginHandler.ts, packages/browser/src/logout/GeneralLogoutHandler.ts, packages/browser/src/logout/__mocks__/LogoutHandler.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts, packages/browser/src/sessionInfo/__mocks__/SessionInfoManager.ts
If the user did not log out, and tries to login in a different tab, data stored in local storage prevents expected behaviour, and the login cannot happen. This fixes the issue byy clearing the storage on login as well as on logout.
=> Clear local storage on login

packages/core/src/storage/__mocks__/StorageUtility.ts
There are a number of annotations listed in our CI: https://github.com/inrupt/solid-client-authn-js/actions/runs/253759683
They all come down to the same lint warning not being respected.
This PR fixes those lint warnings by making return types explicit.
=> Annotate return types where ESLint wants us to

tsconfig.build.json
Since API documentation is generated per-package, they each need to
specify e.g. not to include non-exported files.
(Although TypeDoc allows you to specify its options in your
tsconfig, it does not appear to also follow its `extends`
statements in the way TypeScript does.)
Note: Creating as a draft so Vercel can deploy these API docs, so I can compare them to the current API docs.
=> Align TypeDoc setups

packages/browser/docs/api/redirects.txt
Add redirects for browser API docs that now should point to core API docs
=> Docs: Add redirects to core

packages/browser/docs/api/conf.py, packages/core/docs/api/conf.py
Update navbar to point to https://docs.inrupt.com/developer-tools/javascript/client-libraries/
=> Docs: Fix link to JS docs

package-lock.json, packages/browser/examples/single/script/package-lock.json, packages/browser/examples/single/script/package.json, packages/core/package-lock.json, packages/core/package.json
After #318, Dependabot opened a whole bunch of PRs updating outdated PRs. Because merging them in order takes a long time (after every merge, the other PRs have to be updated again and have their pipelines run), this PR bundles all of those PRs whose pipelines succeeded. If the pipeline of this one still succeeds, we should be relatively safe in merging them all at once.
=> Merge all succeeding Dependabot PRs

.gitignore, packages/browser/__tests__/dpop/DpopHeaderCreator.spec.ts, packages/browser/__tests__/jose/IsomorphicJoseUtility.test.ts, packages/browser/package.json, packages/browser/src/dpop/DpopHeaderCreator.ts, packages/browser/src/dpop/__mocks__/DpopClientKeyManager.ts, packages/browser/src/jose/IsomorphicJoseUtility.ts, packages/core/package.json, packages/oidc-dpop-client-browser/package.json
In order to build a fetch function with a token in its scope, it's easier not to depend on the DI framework to be able to generate the DPoP header, but to be able to simply call a function and to provide it the DPoP key.
This refactoring makes this possible, while remaining backward-compatible with the classes relying on DI to access crypto functions.
=> Refactored crypto/DPoP to be available as standalone functions

CHANGELOG.md, packages/browser/__tests__/index.spec.ts
The types being consumed or produced by the public API are now exported from the entry point.
=> Export public types

packages/browser/__tests__/dpop/DpopClientKeyManager.spec.ts, packages/browser/__tests__/jose/IsomorphicJoseUtility.test.ts, packages/browser/src/dpop/DpopClientKeyManager.ts, packages/oidc-dpop-client-browser/package-lock.json, packages/oidc-dpop-client-browser/package.json, packages/oidc-dpop-client-browser/rollup.config.js, packages/oidc-dpop-client-browser/src/dpop/dpop.spec.ts, packages/oidc-dpop-client-browser/src/dpop/dpop.ts, packages/oidc-dpop-client-browser/src/index.ts
The DPoP key is now generated in the oidc-client-dpop-browser module, and the solid-client-authn-browser modules only calls a high-level function to get a new key.
The key is currently still stored in memory, which we want to change eventually. Also, the crypto libraries relied upon to generate the key require some node builtins, which are provided by rollup plugins for now.
=> Moved key generation to oidc-client-dpop-browser

CHANGELOG.md, package.json, packages/browser/__tests__/ClientAuthentication.spec.ts, packages/browser/__tests__/authenticatedFetch/fetchFactory.spec.ts, packages/browser/__tests__/login/oidc/OidcLoginHandler.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/__tests__/login/popUp/PopUpLoginHandler.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/login/oidc/OidcLoginHandler.ts, packages/browser/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/core/src/ILoginInputOptions.ts, packages/core/src/login/ILoginOptions.ts, packages/oidc-dpop-client-browser/src/dpop/dpop.spec.ts, packages/oidc-dpop-client-browser/src/dpop/dpop.ts, packages/oidc-dpop-client-browser/src/dpop/tokenExchange.spec.ts, packages/oidc-dpop-client-browser/src/dpop/tokenExchange.ts, packages/oidc-dpop-client-browser/src/index.ts
This integrates the DPoP support implemented in the oidc module into the browser module. For consistency, the bearer token exchange is moved to the oidc module as well, so that obtaining either type of token "feels" the same.
After this, the TokenRequester class could be removed, but it will be done in a different PR so that it appears in the git history, so that it is easier to look for.
=> Support requesting a DPoP token

packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/GeneralRedirectHandler.spec.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/browser/src/login/oidc/redirectHandler/GeneralRedirectHandler.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts
If the URL does not contain redirection info as query params, just return an unauthenticated session instead of throwing an error.
Changing this prevents the consuming app to have to worry about the type of IRI it is passing to the library.
=> Return unauthenticated session on invalid redirect url

CHANGELOG.md, packages/browser/__tests__/login/oidc/ClientRegistrar.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/FallbackRedirectHandler.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/ImplicitRedirectHandler.spec.ts, packages/browser/src/dependencies.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/browser/src/login/oidc/redirectHandler/FallbackRedirectHandler.ts, packages/browser/src/login/oidc/redirectHandler/ImplicitRedirectHandler.ts, packages/oidc-dpop-client-browser/src/dcr/clientRegistrar.spec.ts, packages/oidc-dpop-client-browser/src/dcr/clientRegistrar.ts, packages/oidc-dpop-client-browser/src/dpop/tokenExchange.spec.ts, packages/oidc-dpop-client-browser/src/dpop/tokenExchange.ts
This PR fixes two bugs impacting podbrowser:
- The DCR hanged without any error message. Now, it uses fetch instead of window.fetch, the bundler fills the appropriate fetch in, and things seem to work out.
- Handling an IRI with no querystrings resulted in a throw. This had been fixed in cc939e9, but the fix actually introduced another bug preventing the implicit flow to execute. This new version of the fix is more in line with the handler pattern: a fallback handler is introduced, and returns an unauthenticated session if neither the auth code or the access token are present in the URL.
=> Prevents DCR from hanging in React components

e2e/browser/page-models/FetchPage.ts, e2e/browser/page-models/LoginPage.ts, packages/browser/examples/demoClientApp/src/DemoClientApp.js
Internal refactor to use `data-testid` where appropriate, but leave `id` where our demo app needs to find UI elements directly (e.g. to update `enabled/disabled` status, or change text).
=> use data-testid where appropriate, but id too

packages/browser/__tests__/logout/GeneralLogoutHandler.spec.ts, packages/browser/__tests__/sessionInfo/SessionInfoManager.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/dependencies.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts, packages/browser/src/sessionInfo/__mocks__/SessionInfoManager.ts, packages/oidc-dpop-client-browser/src/cleanup/cleanup.spec.ts, packages/oidc-dpop-client-browser/src/cleanup/cleanup.ts, packages/oidc-dpop-client-browser/src/dpop/tokenExchange.ts, packages/oidc-dpop-client-browser/src/index.ts
This PR fixes two bugs: the query strings not being removed of the redirect IRI, and the local storage not being cleared by oidc-client.
Note: still missing some tests, that's why this is a draft.
=> URL and localStorage cleanup

packages/core/__tests__/util/StorageUtility.spec.ts, packages/core/src/storage/StorageUtility.ts, packages/core/src/storage/__mocks__/StorageUtility.ts
This re-applies https://github.com/inrupt/solid-client-authn-js/commit/a28b0b6e2c29b7e72d8f20dd99536425568906b9, which seems to have been lost in when merging the diverged `1.x` branch.
=> Coverage 100% for Core (mostly secure storage) (#368)

packages/oidc-dpop-client-browser/src/cleanup/cleanup.spec.ts, packages/oidc-dpop-client-browser/src/cleanup/cleanup.ts
This is a stopgap solution, until a cleaner fix is found. For some reason, the functions used to clear the local storage that are working in the demo app aren't working for the react components, which is a problem for podbrowser. This enforces a clean slate, preventing previous client ids to be reused.
=> Workaround react components issues with localstorage

.github/workflows/cd-preview.yml
In some cases, semver matching prevents from using the most up-to-date dependencies, which makes it much harder to test the behaviour of a preview branch.
=> Enforces exact version match in prereleases

packages/core/src/login/ILoginOptions.ts
Just tidies up interface usage a little by removing field duplication and extending instead.
=> extend login options to remove duplicated fields

CHANGELOG.md, e2e/browser/test-suite.json, packages/browser/__tests__/authenticatedFetch/fetchFactory.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/examples/single/bundle/src/App.js, packages/browser/src/authenticatedFetch/fetchFactory.ts
Since a DPoP header is scoped to one target IRI, if the request is redirected, the DPoP header is invalid, which results in a 401 unauthenticated. To fix the issue, the fetch must capture the redirection, and replay the request to the actual target IRI.
This is particularly useful when requests target a container, but omit to include the trailing `/`.
Fixes #89.
=> Gracefully handle redirect for DPoP

packages/browser/docs/api/_templates/docs-navbar.html, packages/browser/docs/api/conf.py, packages/core/docs/api/_templates/docs-navbar.html, packages/core/docs/api/conf.py
- Rename in docs menu: JavaScript React SDK to Solid React SDK
- Add PodBrowser to docs top nav
- Use different image
=> DOCS-189: rename to Solid React SDK

packages/browser/docs/api/conf.py, packages/core/docs/api/conf.py
Update docs configuration to remove Beta from the API docs.
=> Docs: Remove Beta banner

.github/workflows/ci.yml
The MacOS environment is unstable, often stalls the CI, and given that our tests run on ubuntu, which is another unix-based environment, it's not a big issue not to run them on MacOS as well.
=> Disabled MacOS environment from the CI

.github/dependabot.yml
Added github-actions to Dependabot YAML so we can pin our CI to specific versions of those actions, and Dependabot will keep them up-to-date.
=> added github-actions to Dependabot YAML

packages/browser/__tests__/login/AggregateLoginHandler.spec.ts, packages/browser/__tests__/login/oidc/AggregateOidcHandler.spec.ts, packages/browser/src/login/AggregateLoginHandler.ts, packages/browser/src/login/oidc/AggregateOidcHandler.ts, packages/browser/src/login/oidc/redirectHandler/AggregateRedirectHandler.ts, packages/browser/src/login/popUp/AggregatePostPopUpLoginHandler.ts, packages/core/__tests__/util/handlerPattern/AggregateHandler.spec.ts, packages/core/src/index.ts, packages/core/src/util/handlerPattern/AggregateHandler.ts
The handler pattern is not environment-specific, and should be located in the core module to avoid code duplication.
Note: in this case, the class is supposed to be internal, and is not re-exported from the browser on purpose.
=> Moved AggregateHandler pattern from browser to core module

packages/core/src/login/oidc/IClient.ts, packages/node/src/login/oidc/ClientRegistrar.spec.ts, packages/node/src/login/oidc/ClientRegistrar.ts, packages/node/src/login/oidc/IssuerConfigFetcher.spec.ts, packages/node/src/login/oidc/OidcLoginHandler.spec.ts, packages/node/src/login/oidc/OidcLoginHandler.ts, packages/node/src/login/oidc/__mocks__/ClientRegistrar.ts, packages/node/src/login/oidc/__mocks__/IssuerConfigFetcher.ts
This implements DCR using "openid-client". With the code in this commit, the login process progresses all the way to the point where the client can redirect the user to the IdP.
Two main files are updated: 
- `OidcLoginHandler`, which depending on the options decides whether to go dynamically register the client or not
- `ClientRegistrar`, which handles the client registration.
=> Dynamic client registration with openid-client

e2e/browser/test-suite-disabled.json, e2e/browser/test-suite.json
Testcafé seems not to play nicely with Cognito, so while we figure it out, ESS e2e tests are disabled.
=> Disabled ESS e2e tests until Cognito is supported

packages/browser/__tests__/ClientAuthentication.spec.ts, packages/browser/__tests__/login/oidc/ClientRegistrar.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/__tests__/login/oidc/refresh/TokenRefresher.spec.ts, packages/browser/__tests__/sessionInfo/SessionInfoManager.spec.ts, packages/core/__tests__/util/StorageUtility.spec.ts, packages/core/src/storage/StorageUtility.ts, packages/core/src/storage/__mocks__/StorageUtility.ts, packages/node/src/ClientAuthentication.spec.ts, packages/node/src/login/oidc/ClientRegistrar.spec.ts, packages/node/src/login/oidc/refresh/TokenRefresher.spec.ts, packages/node/src/sessionInfo/SessionInfoManager.spec.ts
The StorageUtility mock was basically a re-implementation, but with some features missing. Instead, this mocks up the underlying IStorage, and just returns a StorageUtility wrapping up this mocked storage.
The code is much smaller, and it uncovered a couple of bugs in the browser tests.
Note that this change is initially motivated by a feature expected in the Node module, and that was missing for the StorageUtility mocked re-implementation, which was a known issue anyways.
=> Simplified StorageUtility mock

packages/node/src/authenticatedFetch/fetchFactory.spec.ts, packages/node/src/authenticatedFetch/fetchFactory.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts
This uses the DPoP token returned by the IdP to instanciate a fetch function. This authenticated fetch also follows redirects to rebuild a DPoP token if necessary.
This also completes the tests of handleRedirect by checking that the obtained fetch is authenticated.
Note: this replaces https://github.com/inrupt/solid-client-authn-js/pull/621 to resolve merge conflicts by cherrypicking one commit after the other have been merged.
=> Instanciate fetch from returned token

packages/node/src/login/oidc/ClientRegistrar.spec.ts, packages/node/src/login/oidc/ClientRegistrar.ts, packages/node/src/login/oidc/IssuerConfigFetcher.ts
Client registration information was written in one storage, and read from another, which prevented a registered client to be reused. Also, instead of re-discovering the Issuer, it is now rebuilt from cached information to avoid issueing multiple requests to the issuer config in one grant.
=> Read and write DCR info to/from consistent storage

packages/node/src/authenticatedFetch/fetchFactory.spec.ts, packages/node/src/authenticatedFetch/fetchFactory.ts, packages/node/src/login/oidc/redirectHandler/AggregateRedirectHandler.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/node/src/login/oidc/redirectHandler/FallbackRedirectHandler.ts, packages/node/src/login/oidc/refresh/TokenRefresher.ts, packages/node/src/login/oidc/refresh/__mocks__/TokenRefresher.ts, packages/node/src/sessionInfo/SessionInfoManager.ts
This ensures that the authenticated fetch built after having received a Bearer token supports the refresh token flow. On auth failure, the fetch function tries to update its current access token, and retries the request. The refresh token is also rotated if a new token is sent by the issuer.
The DPoP fetch will incorporate a similar logic in an upcoming PR.
=> Bearer-authenticated fetch supports the refresh token flow

CHANGELOG.md, packages/node/src/authenticatedFetch/fetchFactory.spec.ts, packages/node/src/authenticatedFetch/fetchFactory.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts
This enables refreshing a DPoP access token on authentication failure. Redirection is handled at a higher priority than refresh, so that a redirected request may trigger the refresh flow.
Refreshed access and refresh tokens are then kept in the fetch closure to be reused.
This completes the support for the refresh token flow.
=> DPoP-authenticated fetch uses the refresh flow

packages/node/src/storage/FileSystemStorage.spec.ts, packages/node/src/storage/FileSystemStorage.ts
This introduces a new `IStorage` implementation, `FileSystemStorage`, which uses a JSON file on the filesystem as storage. The purpose is to be able to test easily the support for externally-stored tokens (i.e. this isn't intended to be used in a production system). It will also be a good exemple of extension if one wants to support their own storage solution for user credentials.
This only implements the read feature, write and delete will be implemented in separate PRs.
=> Read data from a JSON file

packages/core/src/storage/StorageUtility.spec.ts, packages/core/src/storage/StorageUtility.ts, packages/node/src/ClientAuthentication.spec.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/node/src/login/oidc/refresh/TokenRefresher.spec.ts, packages/node/src/login/oidc/refresh/TokenRefresher.ts, packages/node/src/sessionInfo/SessionInfoManager.spec.ts, packages/node/src/sessionInfo/SessionInfoManager.ts
Using two storages is a requirement in the browser, because we want to expose as little information as possible in the local storage.
In NodeJS, this constraint does not apply, and it's more convenient to store everything in one storage, since the problem of persistent/non-persistent
storage that forces to use the local storage in the browser does not exist on the server side.
=> Only use one storage in NodeJS

.github/workflows/ci.yml, jest.config.js, jest.e2e.config.js, package.json, packages/node/jest.e2e.config.js, packages/node/package.json, packages/node/src/e2e/e2e-test.spec.ts
This runs authenticated e2e tests based on secrets stored in the environment. Note that this required to use the "bootstrap" app in `packages/node/demo/bootstrappedApp/` in order to log in with the demo account into the identity provider, get the credentials, and store them in GH secrets.
=> Implemented authenticated e2e tests

CHANGELOG.md, packages/browser/package.json, packages/browser/webpack.browser.js, packages/browser/webpack.common.js
Resolves #684 (in part)
We use webpack to output a browser bundle, so it should be advertized in the package.json.
Note that this does not add the ES module build. For consistency, I'd like to switch the whole build system to rollup, so I'll make sure the an ES module build is generated and exported after the migration.
=> Add "browser" tag to package.json

CHANGELOG.md, packages/node/src/ClientAuthentication.ts, packages/node/src/authenticatedFetch/fetchFactory.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.ts, packages/node/src/login/oidc/refresh/__mocks__/TokenRefresher.ts
Instead of manually refreshing the token upfront, a lazy evaluation approach was previously implemented: the fetch function was provided an empty access token when logging in a script, additionnally to the refresh token and client credentials. On the first fetch, the absence of credentials returned 401, which triggered a regular refresh flow. Now, instead but instead of pretending we have an access token initially that will be discarded on the first use in order to get a proper access token, we just go through the refresh flow when logging in, which gets us both the access token that we give to the fetch, but also the ID token that gets us the WebID. Note that the access token isn't used in the refresh flow. The empty string was perviously just used to send a fetch that looks …
=> Reads WebID from ID token in refresh flow

CHANGELOG.md, packages/node/src/ClientAuthentication.spec.ts, packages/node/src/ClientAuthentication.ts, packages/node/src/Session.spec.ts, packages/node/src/Session.ts, packages/node/src/e2e/e2e-test.spec.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.spec.ts
This fixes a bug where the WebID was not bubbled up from the login
handler to the session that called said handler, resulting in the WebID
being computed from the ID token, but never actually set on the session.
=> Attach WebID to session when logging in a script

CHANGELOG.md, packages/core/package-lock.json, packages/core/package.json
This adds `ajv` in the runtime dependencies of `solid-client-authn-core`, because it isn't present at the moment while it is a direct dependency. The issue was hidden so far somehow, but using the library in `generate-oidc-token` revealed the issue.
=> Make dependency on ajv explicit

CHANGELOG.md, lerna.json, packages/browser/package-lock.json, packages/browser/package.json, packages/core/package-lock.json, packages/core/package.json, packages/node/package-lock.json, packages/node/package.json, packages/oidc/package-lock.json, packages/oidc/package.json
This PR bumps the version to 1.2.4
=> Prepared CHANGELOG for release 1.2.4

CHANGELOG.md, packages/node/src/login/oidc/OidcLoginHandler.spec.ts, packages/node/src/login/oidc/OidcLoginHandler.ts
Dynamically registering clients gets them stored in localStorage, ready
to be reused after redirection. It was not the case for statically
registered client credentials, which prevented the token exchange to
complete successfully. This resolves the issue, making it possible to
use statically registered clients.
=> Stores static clients when logging in

.github/workflows/ci.yml, packages/node/src/e2e/e2e-test.spec.ts
The end-to-end tests attempt to fetch both public and private
Resources, and depended on a Pod being pre-initialised with known
access permissions.
To make the tests work with any Pod for which the credentials are
provided, we now use the Pod's WebID document as a public resource
(as that is required by the Solid spec to be public), and the Pod
root as a private resource (as that will always exist and usually
not be initialised to be public).
With that, the tests now also run against the production instance of ESS. I've currently used the same credentials as used for the solid-client end-to-end tests, but those can be changed at any time in the environment variables.
I've also aligned the names of the environment variables with those in solid-client. I'll remove the old ones (`CLIENT_ID`, …
=> Remove depdendency on existing data in e2e tests

.github/dependabot.yml
According to [1], Dependabot will automatically recognise Lerna
projects and update all its dependencies in one go. This should
significantly cut down on the noise of four different pull requests
when a shared dependency releases a new version. And since issues
caused by a dependency upgrade are probably similar across the
different packages, it probably makes sense to fix them together as
well.
Question: what do you think about also removing the examples from Dependabot? Since we're not running automated tests against them, we're not verifying whether the updated dependencies actually work, so the automated updates are more performative than anything. Alternatives would be just not updating dependencies (to make sure they keep working), or removing the lock file (to make it clear that …
=> Do not auto-updated individual Lerna packages

packages/browser/package.json
#818 removed the main entry, which causes jest tests that use the browser package to fail. This re-adds the main entry.
=> Add "main" entry back to package.json for browser package

CHANGELOG.md
The loading of environment variables is only used for our own
end-to-end tests, to ease running them locally when having checked
out our source code. It does not affect usage of the library.
=> Remove non-user-facing feature from changelog

packages/browser/README.md, packages/node/README.md
They do not refer to the correct place when the README is displayed
outside of the context of the repository, e.g. on npmjs.com.
=> Remove relative links in READMEs

CHANGELOG.md, packages/browser/__tests__/Session.spec.ts, packages/browser/__tests__/defaultSession.spec.ts, packages/browser/src/Session.ts, packages/browser/src/defaultSession.ts, packages/browser/src/index.ts
These instantiate a single "default session" behind the scenes that
they all operate on. It currently also exposes a
`getDefaultSession()` function to obtain that Session, because
there is no good other way to obtain session info like the current
user's WebID. It might make sense to extend the `login` event to
supply that information.
I also added the unit tests that were not added in #245, because I was considering reverting that to make the tests for this work, but had no way to verify whether I didn't regress on that. It turned out not to be necessary, but I figured it still made sense to keep the test.
=> Add standalone versions of Session methods

.github/workflows/cd-packaging-tests/bundler-parcel/index.ts, .github/workflows/cd-packaging-tests/bundler-parcel/package.json, .github/workflows/cd-packaging-tests/bundler-webpack/package.json, .github/workflows/cd-packaging-tests/bundler-webpack/src/index.js, .github/workflows/cd-packaging-tests/bundler-webpack/webpack.config.js, .github/workflows/cd-packaging-tests/node/commonjs.cjs, .github/workflows/cd-packaging-tests/node/esmodule.mjs, .github/workflows/cd-packaging-tests/node/package.json, .github/workflows/cd-preview.yml, .github/workflows/cd-release.yml
This adds some barebones Parcel, Webpack and Node (both CommonJS and ES Module versions) projects that try to import from SCAB and SCAN, respectively. Building/running those, respectively, should fail if the JS files are not at the right location or not listed correctly, hopefully catching a bunch of potential bugs arising from the packaging process.
=> Verify that importing from the published package works

CHANGELOG.md, packages/browser/__tests__/Session.spec.ts, packages/browser/src/Session.ts
On logout, the `info` property on the sessio object wasn't updated, so
after logout, `session.info.isLoggedIn` still returned true. This is now
fixed.
This PR fixes bug #894.
=> Bugfix: logout did not update session info

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Since the repository hosts multiple packages, and the issue tracker is
at the repo level, issues would be more helpful if they specified which
package exactly is impacted by a bug.
=> Added package entry in issue template

package.json, packages/browser/docs/api/_static/css/inrupt.css, packages/browser/docs/api/_templates/docs-navbar.html, packages/core/docs/api/_static/css/inrupt.css, packages/core/docs/api/_templates/docs-navbar.html, packages/node/docs/api/_static/css/inrupt.css, packages/node/docs/api/_templates/docs-navbar.html
- Commit 1: Adds link to docs home on top nav bar
- Commit 2: Adds social icon links to top nav bar
- Commit 3: rm typedoc-plugin-markdown from top-level packages.json. Its version ("^3.0.7") conflicted with that in the packages.json in the core|browser|node directories ("^3.1.0") and caused typedoc to error).
=> Docs top navbar

packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/__tests__/sessionInfo/SessionInfoManager.spec.ts, packages/browser/package-lock.json, packages/browser/package.json, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts, packages/core/src/index.ts, packages/core/src/storage/IStorageUtility.ts, packages/core/src/storage/StorageUtility.spec.ts, packages/core/src/storage/StorageUtility.ts, packages/core/src/storage/__mocks__/StorageUtility.ts, packages/node/src/e2e/e2e-test.spec.ts
This write information about sessions on resource servers into local storage. When logging in an IdP, the library checks if the resource server that hosts the user's WebID has a `/session` endpoint. If so, information is stored in local storage following this schema:
```
"tmp-resource-server-session-info": {
webId: <the user's WebID>,
sessions: {
<some-resource-server-iri>: {
expires: <some timestamp>
}
}
}
```
Initially, only the resource server hosting the WebID will be persisted, but the model allows additional servers. 
The purpose of this information is to be able (in an upcoming PR) to be able to be aware that one has an active cookie for a given resource server, in order to initialize the session object appropriately. This approach is based on strong assumptions (the WebID is …
=> Feat/session management/rs cookie write

packages/browser/__tests__/ClientAuthentication.spec.ts, packages/browser/__tests__/Session.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/Session.ts, packages/browser/src/authenticatedFetch/fetchFactory.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/node/src/e2e/e2e-test.spec.ts
Unfortunately, regular sessions are lost when the user refreshes
the page or opens a new tab.
While we're figuring out the API for a longer-term solution, as a
temporary workaround some *resource* servers set a cookie that
keeps the user logged in after authenticated requests, and expose
the fact that they set it on a special endpoint.
After login, we store that fact in LocalStorage. This means that we
can now look for that data, and if present, indicate that the user
is already logged in.
Note that there are a lot of edge cases that won't work well with
this approach, so it will be removed in due time.
The type also still needs to be aligned with the write-side, specifically [this one](https://github.com/inrupt/solid-client-authn-js/pull/920/files#diff-659ac87dfd3711f4cfcea3c7bf6970980f47 …
=> Read the temporary session-workaround-cookie

CHANGELOG.md, e2e/browser/ITestConfig.ts, e2e/browser/helpers/login.ts, e2e/browser/page-models/cognito.ts, e2e/browser/test-suite-disabled.json, e2e/browser/test-suite.json, e2e/browser/testSuiteRunner.test.ts
This adds an end-to-end test to prevent regression of the logout-on-refresh issue. Note that the test is only enforced against ESS, since NSS does not implement this resource server side cookie. It will be necessary to update the test when a more permanent, client-side solution is implemented.
=> Feat/session management/rs cookies e2e

jest.config.js
Tests file should not themselves covered by tests, but for some reason the e2e test is reported in the test coverage.
=> Prevent e2e tests inclusion in the coverage

CHANGELOG.md, lerna.json, packages/browser/package-lock.json, packages/browser/package.json, packages/browser/src/storage/BrowserStorage.ts, packages/core/package-lock.json, packages/core/package.json, packages/node/package-lock.json, packages/node/package.json, packages/oidc/package-lock.json, packages/oidc/package.json
This prevents the session constructor from throwing errors, which is especially useful in test frameworks which do not stub window, and in SSR contexts such as Next.js which hand control to a single page app.
This specifically fixes the use-case in which the Session context provider is used from the React SDK, which calls a Session constructor; that constructor throws errors in the initial Node rendering of the page before the single-page-app takes over.
=> Move reference to `window` into a getter

CHANGELOG.md, packages/browser/__tests__/Session.spec.ts, packages/browser/src/Session.ts, packages/node/src/Session.spec.ts, packages/node/src/Session.ts
Resolves #955 
The login even was emitted *before* setting the session info, which
could result in a race where the onLogin callback couldn't read session
information, surch as the WebId.
=> Only emit login event when session info is set

CHANGELOG.md, packages/browser/__tests__/sessionInfo/SessionInfoManager.spec.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts, packages/core/src/index.ts, packages/core/src/login/oidc/redirectHandler/IRedirectHandler.ts, packages/core/src/sessionInfo/ISessionInfo.ts, packages/core/src/sessionInfo/ISessionInfoManager.ts, packages/node/src/ClientAuthentication.ts, packages/node/src/Session.spec.ts, packages/node/src/Session.ts, packages/node/src/index.ts, packages/node/src/sessionInfo/SessionInfoManager.spec.ts, packages/node/src/sessionInfo/SessionInfoManager.ts
getStoredSession is a function that will return a Session based on its
session ID if the provided ID exists in storage. It is mostly useful to
handle multiple sessions on the server side, where the session object
will not always be available in the scope of the function that processes
some data.
=> Feat/1644 multi session/get session from storage

CHANGELOG.md, packages/node/src/Session.spec.ts, packages/node/src/Session.ts, packages/node/src/index.ts
This completes the change from https://github.com/inrupt/solid-client-authn-js/pull/962, where a review comment has been forgotten.
=> Renamed getStoredSession to getSessionFromStorage

CHANGELOG.md, packages/browser/__tests__/ClientAuthentication.spec.ts, packages/browser/__tests__/Session.spec.ts, packages/browser/src/Session.ts, packages/node/src/ClientAuthentication.spec.ts
On the handleIncomingRedirect method of the Session class, set
the current browser URL as the default value, just as a
convenience for the developer.
=> add current URL as default

CHANGELOG.md, packages/browser/src/SessionManager.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts, packages/browser/src/sessionInfo/__mocks__/SessionInfoManager.ts, packages/core/src/sessionInfo/ISessionInfoManager.ts, packages/node/src/ClientAuthentication.spec.ts, packages/node/src/ClientAuthentication.ts, packages/node/src/Session.spec.ts, packages/node/src/Session.ts, packages/node/src/SessionManager.ts, packages/node/src/__mocks__/ClientAuthentication.ts, packages/node/src/constants.ts, packages/node/src/index.ts, packages/node/src/sessionInfo/SessionInfoManager.spec.ts, packages/node/src/sessionInfo/SessionInfoManager.ts, packages/node/src/sessionInfo/__mocks__/SessionInfoManager.ts
This implements the different functions required to list all the known session IDs for a given storage, in order to be able to iterate through them is required. Note that `getSessionFromStorage` returns a Session object, potentially logged in, while `getSessionIdFromStorageAll` only returns the session ids, and it is up to the caller to the manually retrieve individual sessions. This is mostly for performance concerns: logging a session in requires an HTTP interaction, so if multiple sessions need to be logged in at once, that could represent a costly operation (that the server is still able to perform with the proposed API anyway).
=> Feat/1644 multi session/get session from storage all

packages/browser/examples/single/bundle/src/App.js
This changes the browser example to replace explicit session
initialization by default session usage.
=> Updated example to use default session

packages/browser/docs/api/source/index.rst, packages/browser/tsconfig.json
The API docs did not list the functions using the default session, because they were not listed in the toctree. I think this should fix that, but I'll mark this PR as a draft until I can verify for sure that this fixes it in the preview deployment.
=> Also list default session functions in API docs

packages/node/src/Session.spec.ts, packages/node/src/Session.ts, packages/node/src/index.ts, packages/node/src/multiSession.spec.ts, packages/node/src/multiSession.ts, packages/node/tsconfig.json
Functions not exposed by a class, such as `getSessionFromStorage`, were
not listed as part of the public API. This introduces the same issue
that was identified in https://github.com/inrupt/solid-client-authn-js/pull/990
=> List session management functions in the API doc

CHANGELOG.md, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts
Resolves #996 
This prevents a CORS error thrown by an internal fetch to bubble up an
discrupt the login flow. Note that this is part of a temporary code
snippet that will be removed once a longer-term solution for auth after
refresh is implemented.
=> Swallow exception when looking up custom endpoint

CHANGELOG.md, packages/browser/src/sessionInfo/SessionInfoManager.ts
Instead of retrieving the WebID from the session information, which
aren't avalaible when the session has been restored in a new tab,
it is retrieved from local storage in the temporary RS cookie fix.
The absence of the WebID prevented the cookie workaround to be cleared,
forcing a session active in multiple tabs to remain open.
=> Retrieve WebID from stored RS cookie

packages/browser/src/Session.ts, packages/browser/src/defaultSession.ts, packages/node/src/Session.ts
Tweak API documentation:
- Remove the word "magic"
- Fix missing right square bracket ] for link
- Add link to getDefaultSession from the Session constructor. Because we do some processing for the defaultSession functions for their new destination page, could not use the {@link } or [[ link ]] typedoc linking since those would link to pre-processing index.html page instead.
=> API Docs: tweak wording;add/fix link

CHANGELOG.md, packages/browser/__tests__/Session.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/Session.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/core/src/sessionInfo/ISessionInfo.ts, packages/oidc/src/dpop/tokenExchange.spec.ts, packages/oidc/src/dpop/tokenExchange.ts
When the session expired, `session.info.isLoggedIn` would still be `true`, and there was no way for the developer to know that the session was no longer valid.
With this change, we check the expiration time as sent by the server, add it to a timestamp we generated _before_ sending a request to the server (to ensure we're not running behind), and then log the session out when it expires (this also generates a `logout` event).
=> Log the user out when the session expires

packages/browser/.eslintrc.js, packages/browser/__tests__/ClientAuthentication.spec.ts, packages/browser/__tests__/authenticatedFetch/headers/HeadersUtils.spec.ts, packages/browser/__tests__/index.browser.spec.ts, packages/browser/__tests__/login/oidc/OidcLoginHandler.spec.ts, packages/browser/__tests__/login/oidc/Redirector.spec.ts, packages/browser/__tests__/login/oidc/TokenRequester.spec.ts, packages/browser/__tests__/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/__tests__/sessionInfo/SessionInfoManager.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts, packages/browser/src/login/webid/WebIdLoginHandler.spec.ts, packages/browser/src/login/webid/WebIdLoginHandler.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts, packages/browser/src/storage/BrowserStorage.spec.ts, packages/browser/src/util/urlPath.spec.ts, packages/core/src/sessionInfo/ISessionInfo.ts
Store the current browser URL in local storage if we have a stored ID token - in the `handlerIncomingRedirect()` function.
Also raised test coverage to 100% (apart from files we know we want to remove, which we should do soon really).
This PR bumps the version to <version number>.
=> store current URL in handlerIncomingRedirect

packages/browser/__tests__/ClientAuthentication.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/__tests__/sessionInfo/SessionInfoManager.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/__mocks__/ClientAuthentication.ts, packages/browser/src/constant.ts, packages/browser/src/login/oidc/__mocks__/IssuerConfigFetcher.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts, packages/browser/src/storage/__mocks__/LocalStorage.ts, packages/core/src/index.ts, packages/core/src/sessionInfo/ISessionInfo.ts, packages/core/src/sessionInfo/ISessionInfoManager.ts
This adds the method `getCurrentIssuer` to the ClientAuthentication class.
Based on the current session ID in storage, the associated ID token is
validated, before returning its issuer to the caller. This way, we ensure
that the ID token hasn't been tampered with, that its audience is the
client associated to the current session, and that the issuer hasn't
been changed in storage either.
=> Verify ID token when looking up current issuer 

CHANGELOG.md, packages/browser/__tests__/login/oidc/OidcLoginHandler.spec.ts, packages/browser/src/login/oidc/ClientRegistrar.ts, packages/browser/src/login/oidc/OidcLoginHandler.ts, packages/browser/src/login/oidc/__mocks__/ClientRegistrar.ts
This PR fixes bug #.
The 'client_id' option, if specified as an option when logging in, is now  stored in storage, ready to be retrieved again from storage when the login  flow redirects back to the client application (previously it was only being stored if DCR was invoked).
=> login handler now always stores client_id in storage

packages/browser/__tests__/ClientAuthentication.spec.ts, packages/browser/__tests__/Session.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/Session.ts, packages/browser/src/__mocks__/ClientAuthentication.ts
This refactors code introduced in
1b4357f6b02327cf03ecf6d478392fdafc59e5ea. In the original design, the
current IRI was stored after successful login, while actually it makes
more sense to only store it during the silent authentication process,
right before silently redirecting the user away from the app, in case
client-side navigation happened and the user refreshes a page that is no
longer the one he logged in to.
For context, this is the first step to silent authentication: after a
refresh, the access token is no longer available. To log back in, the
use must be redirected to the IdP, and storing the current IRI before
redirecting makes it easier to restore it after the user is logged back
in.
=> Store current IRI before silent authentication

packages/browser/__tests__/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/login/oidc/OidcLoginHandler.ts, packages/browser/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts, packages/core/src/login/ILoginOptions.ts, packages/core/src/login/oidc/IOidcOptions.ts
This enables to specify the "prompt" option from our own internal API
all the way down to the OIDC library we are using. The "prompt" option,
when set to 'none', prevents the Identity Provider to display any screen
or to have any sort of user interaction, which is what we want for
silent authentication.
Note that the "prompt" option was not added to
the external API, because there is no reason for the calling library to
decide it needs to go through silent authentication: we make this call
entierly based on internal state. The code to implement this logic of
whether we want or not to go through silent authentication is not part
of this PR.
=> Add internal support for silent authentication

packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/__tests__/sessionInfo/SessionInfoManager.spec.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts, packages/core/src/sessionInfo/ISessionInfo.ts
In order to do silent authentication, one must provide a redirect URL
(like for regular login). In order to do so, on successful login, the
redirect URL is stored with the session information, so that it can be
retrieved after refresh and be used to trigger silent authentication.
Note to reviewers: even if this is related to the same feature as #1076 , these two PRs are independant from each other and can be reviewed in any order.
=> Add redirectUrl to stored session info

CHANGELOG.md, packages/browser/__tests__/login/oidc/OidcLoginHandler.spec.ts, packages/browser/src/login/oidc/OidcLoginHandler.ts, packages/node/src/login/oidc/OidcLoginHandler.spec.ts, packages/node/src/login/oidc/OidcLoginHandler.ts
The user provides an issuer IRI, which allows discovering the issuer
configuration. So far, this user-provided IRI was stored on login, and
used to validate the ID token. However, this IRI may be correct, but
still differ from the issuer claim of the ID token, e.g. depending on
whether it includes a trailing slash or not. Now, the IRI that gets
stored is the canonical IRI obtained from the IdP's config, which
enforces it to be aligned with the ID token's issuer claim.
=> Get issuer canonical IRI from its own config

CHANGELOG.md, packages/browser/__tests__/ClientAuthentication.spec.ts, packages/browser/__tests__/Session.spec.ts, packages/browser/__tests__/sessionInfo/SessionInfoManager.spec.ts, packages/browser/src/Session.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts, packages/core/src/sessionInfo/ISessionInfo.ts, packages/oidc/src/dpop/dpop.spec.ts, packages/oidc/src/dpop/dpop.ts
This implements silent authentication e.g. after a refresh. To do so, it was necessary to retrieve client secrets with session information from storage, in order to provide them when calling `login` to trigger the silent flow. This includes a couple of fixes required for silent authentication to work, including validating ID tokens signed with RSA algorithms, and making sure that all relevant session information (in particular, the ID token) was stored in the permanent storage.
This simply redirects the user away from the page, and straight back from the Solid Identity Provider. The incoming redirect is identical to an incoming redirect for a regular login, which is why no dedicated code was added to that end.
=> Trigger silent authentication

packages/browser/docs/api/_templates/docs-navbar.html, packages/core/docs/api/_templates/docs-navbar.html, packages/node/docs/api/_templates/docs-navbar.html
Update API docs top navbar: Enterprise Solid Server link should go to docs.inrupt.com/ess/latest.
Rendered: https://solid-client-authn-js-hzziuoflz-inrupt.vercel.app/core/
=> DOCS: navbar ess -> ess/latest

package.json
When setting up husky v5, a behaviour of the build toolchain was
changed: the build script was no longer running when running the install
script. Because there are dependencies between the packages of the
monorepo, running this build script is actually useful, and this
re-enables this behaviour.
=> R-enable running build script on install

.github/publish-website.yml, .github/workflows/codeql-analysis.yml, packages/browser/README.md, packages/browser/docs/api/conf.py, packages/core/docs/api/conf.py, packages/node/docs/api/conf.py, packages/oidc/package.json
This should replace all references to `master` in the codebase. Before merging this, I'll change the branch protection rules, and use GH's UI to rename the branch so that open PRs get migrated.
=> Renamed master branch to main

CHANGELOG.md, packages/browser/__tests__/Session.spec.ts, packages/browser/src/Session.ts
Attempting to restore a session loses the application state, so it
should be a conscious decision by developers to do so, and to take
the opportunity to preserve and restore the state themselves.
This fixes a bug introduced in 1.6.0.
=> Do not enable session restore by default

.github/workflows/cd-preview.yml, .github/workflows/cd-release.yml, .github/workflows/ci.yml
The upload-artifact action is notoriously unreliable, but it is not
important enough to break the build when it fails. Rather, we can
just restart the build in the rare occasion that we do need those
artifacts and the upload fails.
=> Don't fail the build when coverage upload fails

CHANGELOG.md, packages/browser/__tests__/Session.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/__tests__/sessionInfo/SessionInfoManager.spec.ts, packages/browser/src/Session.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts, packages/core/src/index.ts, packages/core/src/storage/IStorageUtility.ts, packages/core/src/storage/StorageUtility.spec.ts, packages/core/src/storage/StorageUtility.ts, packages/core/src/storage/__mocks__/StorageUtility.ts
This reverts d7332cf00317a7a3bc1f3684c01916bd21f89ace, but adds
that the Resource Server cookie-based workaround is only enabled
when silent token refresh is not enabled, to ensure that that is a
non-breaking bugfix.
This means I only added a single test (Session "does not attempt to use the workaround if the long-term solution (silent refresh) is enabled") and the second condition in
```js
if (
typeof storedSessionCookieReference === "string" &&
options.restorePreviousSession !== true
) {
```
=> Re-enable workaround with disabled silent refresh

CHANGELOG.md, lerna.json, packages/browser/package-lock.json, packages/browser/package.json, packages/core/package-lock.json, packages/core/package.json, packages/node/package-lock.json, packages/node/package.json, packages/oidc/package-lock.json, packages/oidc/package.json
This PR bumps the version to 1.6.1.
=> Release v1.6.1

CHANGELOG.md, packages/browser/__tests__/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/core/src/storage/StorageUtility.spec.ts, packages/core/src/storage/StorageUtility.ts, packages/node/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/node/src/login/oidc/refresh/TokenRefresher.spec.ts, packages/oidc/src/dpop/tokenExchange.spec.ts, packages/oidc/src/dpop/tokenExchange.ts
Parts of the code reads and writes the redirect URI in storage with the key `redirectUri`, and some other parts with the key `redirectUrl`. This causes confusion, and ends up with potentially creating a bug when trying to use one in silent authentication when the other is the one that has been registered as valid by the Solid Identity Provider, leading to the user being displayed an `invalid_grant` screen instead of being redirected to the app.
Technically, either `redirectUrl` or `redirectUri` are valid choices.
`redirectUrl` has been picked because it is the name of the parameter in
the login options, so picking `redirectUri` woud need either breaking
change, or to keep some room for error by having to rename the field in
the JSON object at some point. Note that the actual OAuth …
=> Removed duplication between redirectUr(i|l)

CHANGELOG.md, packages/browser/__tests__/Session.spec.ts, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/examples/single/bundle/src/App.js, packages/browser/src/Session.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts
So far, logging in to any Identity Provider would lead to the Resource
Server hosting the WebID being looked up for a `/session` endpoint. This
causes several issues:
- It makes additional, non-required requests if the server does not have
a session endpoint, or if the app supports silent authentication
- It has caused annoying issues when looking up the missing endpoint for
some servers
- It's a solution we want to deprecate anyways.
To resolve this, both the endpoint lookup and the cookie-based auth can
be disabled by specifying an additional option to
`handleIncomingRedirect`, `useEssSession`. It defaults to true (for
backward-compatibility), but it is considered false if silent
authentication is enabled.
Note that this uses an entry in local storage to share the state between
the …
=> Enable ESS cookie auth opt out

packages/browser/src/Session.ts
Technically someone could be using the interface somewhere in the code and this would be breaking, but in practice I'm quite sure nobody does, so as far as I'm concerned we don't need to preserve the one with the typo. Happy to add it if you disagree though.
=> Fix typo in interface name

.github/pull_request_template.md
The command currently suggested (namely `lerna version <major|minor|patch> --no-push`) modifies some files before commit, which fails the operation, since uncommited changes are present. For some reason, running the same command in an NPM script prevents the issue from happening.
=> Change the version command in PR template

.github/workflows/cd-preview.yml, .github/workflows/cd-release.yml
Due to https://github.com/parcel-bundler/parcel/issues/5943, using the
latest parcel version (1.12.4 at the time of writing) breaks the build.
This pins the parcel version for the CD to work again, until the
upstream bug is resolved.
=> Pin parcel version

.github/pull_request_template.md, .github/workflows/cd-preview.yml, package.json
Internal change - just renaming the `package.json` script to run `lerna version...` to prevent the easy-to-make mistake of forgetting to add the 'run' keyword when running `npm run version...`.
=> name Lerna version script more explicitly

CHANGELOG.md, packages/oidc/src/cleanup/cleanup.spec.ts, packages/oidc/src/cleanup/cleanup.ts
The hash fragment in an URI is only meant to be useful client-side, and
it is forbidden in a redirect URI (see
https://tools.ietf.org/html/rfc6749#section-3.1.2). This adds a step in
the URI cleanup function to remove the hash fragment of the provided
URI.
=> Remove hash fragment in URL sanitation

.github/workflows/ci.yml, package.json
lerna requires a specific audit configuration, enabled by the package
lerna-audit. It now runs in CI along with the regular `npm audit`.
The script is also now named `lerna-audit` instead of `audit` to avoid
the confusion with the `npm audit` command.
=> Enable lerna-audit in CI

CHANGELOG.md, packages/browser/__tests__/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/login/oidc/IssuerConfigFetcher.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts
When receiving an ID token from the token endpoint, it is validated
(e.g. the signature is checked, and the issuer and audience are matched
against expected values).
Validating the ID token is something the client app should do anyways in OIDC. Validation already happens in the library we are using when requesting a bearer token (and in the node library as well), so it was only missing when requesting a DPoP-bound access token in the browser code. Validating the ID token is even more important with client access control, because the ID token's audience (the client id) is also present as the `client_id` claim in the access token, and it is going to be matched against the `acp:client` predicate to validate access control, so if the IdP doesn't use the right client id, access control won't …
=> Vvalidate ID token

CHANGELOG.md, packages/node/src/ClientAuthentication.spec.ts, packages/node/src/ClientAuthentication.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts
- The IRI wasn't normalized on input
- The IRI parameters added by the Solid Identity Provider were not
removed from the redirect_iri specified at the token endpoint. This was causing a mismatch between the provided `redirect_iri` and the expected value, equal to the `redirect_iri` provided during registration.
These two bugs combined could cause the behaviour observed by @jeff-zucker in https://github.com/solid/node-solid-server/issues/1580.
=> Normalize redirect IRI in node package

packages/browser/__tests__/login/oidc/IssuerConfigFetcher.spec.ts, packages/browser/src/login/oidc/IssuerConfigFetcher.ts, packages/core/src/login/oidc/IIssuerConfig.ts, packages/node/src/login/oidc/IssuerConfigFetcher.spec.ts, packages/node/src/login/oidc/IssuerConfigFetcher.ts
This is the preliminary step to figure out how to interact with a Solid
Identity Provider: when fetching its description as part of the OIDC
discovery process (see
https://openid.net/specs/openid-connect-discovery-1_0.html for more
informaiton), support for Solid-OIDC is specified with the
`solid_oidc_supported` key, as specified in
https://solid.github.io/authentication-panel/solid-oidc/#discovery.
Additional PRs will take this configuration into account to perform DCR
or present a client WebID, the latter being only supported by Solid-OIDC
conformant OIDC providers.
=> Discover support for solid-oidc in OIDC provider

CHANGELOG.md, packages/browser/__tests__/login/oidc/OidcLoginHandler.spec.ts, packages/browser/src/login/oidc/IssuerConfigFetcher.ts, packages/browser/src/login/oidc/OidcLoginHandler.ts, packages/core/src/index.ts, packages/core/src/login/oidc/IClientRegistrar.test.ts, packages/core/src/login/oidc/IClientRegistrar.ts, packages/node/src/login/oidc/OidcLoginHandler.spec.ts, packages/node/src/login/oidc/OidcLoginHandler.ts
This adds support for client WebID in the login process. There are a
certain number of configurations to consider: either the IdP supports
Solid-OIDC or not, and either the client provides a client_id or not.
If no client_id is provided, dynamic client registration is required,
regardless of the IdP. Most clients fall into this category today. If a
client ID is provided and it doesn't look like an IRI, or if it is an
IRI and the IdP supports Solid-OIDC, the client can be considered
already registered and there is no additional interaction required.
The library only has to be careful when the client provides a client
WebID, but the IdP soes not support Solid-OIDC.In that case, presenting
the client_id to the IdP would fail, because it would not look up the
app profile, but expect the given …
=> Handle Solid-OIDC client WebID

.github/workflows/cd-preview.yml, .github/workflows/cd-teardown.yml, .github/workflows/ci.yml, .github/workflows/e2e-browser.yml
The current `'dependabot'` does not skip jobs as expected, and according to https://dev.to/github/conditional-workflows-and-failures-in-github-actions-2okk or https://github.com/marketplace/actions/auto-approve-dependabot it looks like the actor should actually be `dependabot[bot]`.
=> Changed GH actor to dependabot[bot]

.github/workflows/e2e-browser.yml
Skipping the event that triggers the deployment hangs the event waiting
fot the deployment instead of skipping it too. Now, the browser e2e test
are skipped for dependabot too.
=> Skip e2e browser tests for dependabot

.github/workflows/e2e-browser.yml
This applies a different trigger to the e2e browser tests to skip the
workflow altogether for dependabot PRs, because dependabot does not have
access to GH secrets (also, the tests are flaky, and don't add value to most dependabot PRs). It should still be possible to manually run the
tests.
=> Do not trigger browser e2e test for dependabot

CHANGELOG.md, packages/browser/__tests__/Session.spec.ts, packages/browser/src/Session.ts, packages/browser/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts
There appears to be a race condition when logging in, that does not
manifest consistently. When it does, session information aren't stored
properly in local storage, resulting in a failure after redirection.
I suspect this causes #1242.
=> Prevent race condition on login

CHANGELOG.md, packages/oidc/src/dpop/tokenExchange.spec.ts, packages/oidc/src/dpop/tokenExchange.ts
When the token endpoint returns an error, said error is now bubbled back up
to the developer properly, instead of being wrapped in a seemingly
unrelated error message pointing out the absence of an access token.
=> Handle token endpoint error appropriately

packages/browser/docs/api/requirements.txt, packages/core/docs/api/requirements.txt, packages/node/docs/api/requirements.txt
Pin 3rd party docs theme requirement to a version.
=> apidocs: pin docs theme requirements

CHANGELOG.md, packages/core/src/ILoginInputOptions.ts, packages/core/src/login/ILoginOptions.ts, packages/core/src/login/oidc/IOidcOptions.ts, packages/core/src/login/oidc/redirectHandler/IRedirectHandler.ts, packages/node/example/bootstrappedApp/src/authenticatedScript.ts, packages/node/src/ClientAuthentication.spec.ts, packages/node/src/ClientAuthentication.ts, packages/node/src/Session.ts, packages/node/src/authenticatedFetch/fetchFactory.spec.ts, packages/node/src/authenticatedFetch/fetchFactory.ts, packages/node/src/login/oidc/OidcLoginHandler.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/node/src/login/oidc/refresh/TokenRefresher.spec.ts, packages/node/src/login/oidc/refresh/TokenRefresher.ts, packages/node/src/login/oidc/refresh/__mocks__/TokenRefresher.ts, packages/node/src/multiSession.ts
In order to allow for some use cases where using the storage isn't the
most practical solution, this makes it possible to run some custom code
when getting an access token. Two paths are considered:
- when initially logging in, when the refresh token is returned as a
response from the token endpoint. In this case,
`session.handleincomingRedirect` accepts a new parameter,
`handleRefreshToken`, which allows the caller to run custom code at this
point. An example usage for this would be to replace the current
behaviour of `generate-oidc-token`, which looks into the storage to get
the refresh token, and which could instead use this handler.
- when using a refresh token to get a new access token. In this case,
the refresh token may be rotated by the identity provider. The
`session.login` …
=> Add refresh token handling hooks

CHANGELOG.md, packages/browser/__tests__/ClientAuthentication.spec.ts, packages/browser/__tests__/Session.spec.ts, packages/browser/examples/single/bundle/package.json, packages/browser/examples/single/script/package.json, packages/browser/src/ClientAuthentication.ts, packages/browser/src/Session.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts
The calls to /session that resulted in 404s were confusing to
developers, and a less brittle workaround is now available with
`restorePreviousSession`. ESS has also disabled the option by
default.
=> Disable ESS-specific session workaround by default

.github/workflows/ci.yml
The current auth workaround, i.e. using an NSS instance as our Solid
Identity Provider, isn't very helpful, because it keeps timing out, and
that's introducing a weird bug where Jest never completes the tests.
It complains that some async code never resolved, but when using the
proposed debug method (`--detectOpenHandles`) the bug doesn't manifest
clearly, and it's a pain to debug.
Given that we're looking at changing this approach anyway, this
disables e2e tests instead of trying to figure out how to work with
NSS, which we know has some performance issues.
=> Skip node e2e tests in CI

packages/browser/__tests__/ClientAuthentication.spec.ts, packages/browser/__tests__/Session.spec.ts, packages/browser/__tests__/sessionInfo/SessionInfoManager.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/Session.ts, packages/browser/src/sessionInfo/SessionInfoManager.ts, packages/core/src/index.ts, packages/core/src/sessionInfo/ISessionInfo.spec.ts, packages/core/src/sessionInfo/ISessionInfo.ts
This internal refactor simply changes some internal interfaces (so it's a non-breaking change) in order to make the configuration of iframe-based behaviour cleaner. This mostly intends at removing duplication between login options objects at the different levels (Session, ClientAuthentication, OIDC handler). Note that this change doesn't contain anything iframe-based yet, this is just a preparatory PR to make review easier.
=> Cleanup login options

packages/browser/docs/api/Makefile
The docs Makefile in the browser package had a space instead of a tab which caused the line (git clone) not to be run - so that the browser docs weren't building.
https://solid-client-authn-js-9m80jzl6n-inrupt.vercel.app/browser/
https://solid-client-authn-js-9m80jzl6n-inrupt.vercel.app/node/
https://solid-client-authn-js-9m80jzl6n-inrupt.vercel.app/core/
=> Docs: Fix makefile to use tab

.github/workflows/cd-teardown.yml
We don't automatically publish dependabot PRs, because that would
require exposing a token that allows that to code in that PR.
However, this means that after merging such a PR, there is no
preview package to unpublish. This commit ensures that it then does
not attempt to do so.
=> Only unpublish published review packages

e2e/browser/helpers/authorizeClientApp.ts
Unfortunately using the `.withText` selector didn't seem to work
for one reason or another. Investigating why didn't seem worth the
effort, hence just matching on the DOM structure for now.
=> Update browser-based E2E tests for broker changes

CHANGELOG.md, packages/browser/__tests__/Session.spec.ts, packages/browser/__tests__/util/UUIDGenerator.spec.ts, packages/browser/src/Session.ts
If login() doesn't error, it redirects the user away from the page,
so any code following it will not reliably succeed. (The Promise
cannot be suppressed as a whole, since errors can still occur which
should result in a rejected Promise.)
=> Do not resolve the login() Promise on success

CHANGELOG.md, packages/browser/__tests__/Session.spec.ts, packages/browser/src/Session.ts, packages/browser/src/iframe.ts
This PR fixes the bug where `handleIncomingRedirect` does not resolve when attempting, but failing (e.g. when the session on the IDP has expired), to silently authenticate. This, in turn, causes solid-ui-react to never set `sessionRequestInProgress` to `false`, which then caused PodBrowser to keep attempting to login.
=> Fix session restore loop

CHANGELOG.md, lerna.json, packages/browser/package-lock.json, packages/browser/package.json, packages/core/package-lock.json, packages/core/package.json, packages/node/package-lock.json, packages/node/package.json, packages/oidc/package-lock.json, packages/oidc/package.json
This PR bumps the version to 1.9.0.
=> Release v1.9.0

.github/workflows/e2e-browser.yml, e2e/browser/.gitignore, e2e/browser/package.json
Just adds a new `package.json` script to run End-2-End tests with pre-configured options as used by CI (so we can more concisely re-run the End-2-End tests multiple times from the CI YAML).
=> Re-run CI E2E tests on failure (max 3 times (currently))

CHANGELOG.md, packages/browser/package-lock.json, packages/browser/package.json
We used to make the assumption that native Node modules would
automatically get polyfilled by whatever bundlers developers were
using to get code to run in the browser. However, at least Webpack
5 no longer does that.
Since our upgrade to jose@3 (aka @inrupt/jose-legacy-modules), the
only native module we were still referencing is `events`. Since
it's only the Session class referencing/extending it, we could
probably also consider updating that to no longer do so and just
handle callbacks for the various session events itself, but until
then, this should ensure developers no longer manually have to add
those polyfills.
This PR fixes bug #1099 (or at least the last remnant of it).
=> Add the `events` polyfill as a direct dependency

CHANGELOG.md, packages/core/src/authenticatedFetch/dpopUtils.ts, packages/core/src/storage/StorageUtility.spec.ts, packages/core/src/storage/StorageUtility.ts, packages/node/src/authenticatedFetch/fetchFactory.spec.ts, packages/node/src/login/oidc/ClientRegistrar.spec.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts
This adds support for DPoP-bound refresh tokens. Effectively, the biggest change is that instead of re-generating a DPoP key when going through the refresh flow, we now have to store the DPoP key when it is issued and reuse it as we go. This does not introduce additional vulnerabilities, as a DPoP-bound refresh token leaking with its DPoP key is just as bad as an unbound refresh token leaking.
Note that the DPoP key was only regenerated as part of the refresh token login flow, but the previous key kept being reused in the refresh flow initiated from within the fetch closure. This is why 07c2fdd only introduces a test: the expected behaviour happened to be already implemented, we just had to prevent regression.
Note that storing the DPoP key is only appropriate in Node, and will not be …
=> Support DPoP-bound refresh tokens

CHANGELOG.md, lerna.json, packages/browser/package-lock.json, packages/browser/package.json, packages/core/package-lock.json, packages/core/package.json, packages/node/package-lock.json, packages/node/package.json, packages/oidc/package-lock.json, packages/oidc/package.json
This PR bumps the version to 1.10.1.
=> 1.10.1 release

CHANGELOG.md, packages/browser/examples/single/bundle/client-app-profile.ttl, packages/browser/src/login/oidc/ClientRegistrar.spec.ts, packages/browser/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.spec.ts, packages/browser/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts, packages/oidc/src/dcr/clientRegistrar.spec.ts, packages/oidc/src/dcr/clientRegistrar.ts
This as the browser set the `offine_access`  scope on its token request, which effectively asks a refresh token from the OIDC provider. In order to be able to use this token, dynamically registered clients must also specify that they may use the `refresh_token` grant at registration.
PS: leaving this as a draft until I've run a manual e2e test.
=> Ask for offline scope in browser

packages/core/src/authenticatedFetch/fetchFactory.spec.ts, packages/core/src/authenticatedFetch/fetchFactory.ts, packages/core/src/index.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts
This reduces a lot code duplication by merging `buildDpopFetch` and
`buildBearerFetch` in a single `buildAuthenticatedFetch` function, which previously existed but delegated to the other two. It will make the implementation of proactive refresh tokens easier, because only one place will need to be updated, as there was a fair amount of duplication between the previous two functions.
The present commit does change any features, it's only a refactoring to
facilitate upcoming feature implementation.
=> Consolidate the fetch factory

packages/oidc/src/refresh/refreshGrant.spec.ts, packages/oidc/src/refresh/refreshGrant.ts
The expiration date returned by the OIDC provider wasn't returned along
with the refreshed access token.
=> Set expiration date during refresh grant

CHANGELOG.md, packages/browser/src/Session.spec.ts, packages/browser/src/Session.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/browser/src/login/oidc/redirectHandler/ErrorOidcHandler.ts, packages/core/src/authenticatedFetch/fetchFactory.spec.ts, packages/core/src/authenticatedFetch/fetchFactory.ts, packages/core/src/constant.ts, packages/core/src/errors/InvalidResponseError.ts, packages/core/src/errors/OidcProviderError.ts, packages/core/src/index.ts, packages/node/src/login/oidc/oidcHandlers/ClientCredentialsOidcHandler.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/oidc/src/dpop/tokenExchange.spec.ts, packages/oidc/src/dpop/tokenExchange.ts, packages/oidc/src/refresh/refreshGrant.spec.ts
When using refresh tokens to keep the session alive, for some reason the
silent authentication may fail. In this case, we want to notify the app
that it no longer is authenticated, and that it should prompt the user
for re-authentication.
=> Error handling on silent authentication

.eslintrc.js, packages/browser/src/ClientAuthentication.spec.ts, packages/browser/src/Session.spec.ts, packages/browser/src/iframe.spec.ts, packages/browser/src/login/oidc/ClientRegistrar.spec.ts, packages/browser/src/login/oidc/IssuerConfigFetcher.spec.ts, packages/browser/src/login/oidc/OidcLoginHandler.spec.ts, packages/browser/src/login/oidc/Redirector.spec.ts, packages/browser/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.spec.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/browser/src/util/UUIDGenerator.spec.ts, packages/core/src/authenticatedFetch/fetchFactory.spec.ts, packages/core/src/errors/errors.spec.ts, packages/core/src/login/oidc/redirectHandler/IRedirectHandler.spec.ts, packages/core/src/util/handlerPattern/AggregateHandler.spec.ts, packages/node/src/ClientAuthentication.spec.ts, packages/node/src/Session.spec.ts, packages/node/src/authenticatedFetch/headers/HeadersUtils.spec.ts, packages/node/src/dependencies.spec.ts, packages/node/src/login/oidc/ClientRegistrar.spec.ts, packages/node/src/login/oidc/IssuerConfigFetcher.spec.ts, packages/node/src/login/oidc/OidcLoginHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/ClientCredentialsOidcHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.spec.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/node/src/multiSession.spec.ts, packages/node/src/util/UuidGenerator.spec.ts, packages/oidc/src/dpop/tokenExchange.spec.ts, packages/oidc/src/refresh/refreshGrant.spec.ts
This updates ESLint rules to allow for explicit any in test files,
because it's usually a legitimate use case.
=> Allow 'any' in test files

CHANGELOG.md, packages/browser/src/login/oidc/ClientRegistrar.spec.ts, packages/browser/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/node/src/login/oidc/__mocks__/IssuerConfigFetcher.ts, packages/oidc/src/dcr/clientRegistrar.spec.ts, packages/oidc/src/dcr/clientRegistrar.ts, packages/oidc/src/dpop/tokenExchange.spec.ts
This fixes https://github.com/inrupt/solid-client-authn-js/issues/1551,
and ensures that during Dynamic Client Registration, the
`subject_type` parameter is properly set to `public`, and not to
`pairwise`. Indeed, in Solid, the subject identifier is the WebID, which
is global and unique: it should be shared among all clients. Having the
OP generate a different subject claim for each client for a given
subject does not make sense in the context of Solid.
=> Use subject_type public during DCR

CHANGELOG.md, packages/core/src/authenticatedFetch/fetchFactory.spec.ts, packages/core/src/authenticatedFetch/fetchFactory.ts, packages/core/src/constant.ts, packages/node/example/bootstrappedApp/package-lock.json, packages/node/example/bootstrappedApp/package.json, packages/node/example/bootstrappedApp/src/authenticatedScript.ts, packages/node/src/Session.spec.ts, packages/node/src/Session.ts
The silent authentication running in the background prevents Node from
closing gracefully. This ensures that on logout, the latest timeout set
is cleared, so that no timeout is left hanging after the sessions have
been logged out.
This PR fixes bug #1623 .
=> Clear timeouts on logout

packages/browser/examples/single/bundle/client-app-profile.ttl, packages/browser/examples/single/bundle/package-lock.json, packages/browser/examples/single/bundle/package.json, packages/browser/examples/single/bundle/src/App.js
- The dev depdendencies now pull in Webpack 5.x
- The client profile now contains the 'refresh_token' grant type
This is done in part to investigate https://forum.solidproject.org/t/inrupt-solid-client-authn-browser-1-11-0-process-is-not-defined/4589.
=> Updated dependencies and client profile

.github/workflows/ci.yml, e2e/browser/test-suite.json, packages/node/src/e2e/e2e-test.spec.ts
This sets up the end-to-end tests to run against dev-next, the pre-production ESS environment. These tests are currently failing, and fixing them will be done in a different PR.
In particular, these tests look for actual resources in the Pod which are not created at the moment,
causing the tests to fail. Creating the resources requires some extra setup on the
dev-next environment, which shall be done later.
=> Setup end-to-end tests against dev-next

CHANGELOG.md, packages/browser/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.spec.ts, packages/browser/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts, packages/node/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts, packages/node/src/login/oidc/oidcHandlers/ClientCredentialsOidcHandler.ts
As per https://solid.github.io/solid-oidc/#webid-scope, the request to the token endpoint includes a `webid` scope so that the returned token will have a webid claim.
=> Add the webid scope

CHANGELOG.md, packages/node/src/constant.ts, packages/node/src/login/oidc/ClientRegistrar.spec.ts, packages/node/src/login/oidc/ClientRegistrar.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.spec.ts, packages/node/src/login/oidc/redirectHandler/AuthCodeRedirectHandler.ts, packages/node/src/login/oidc/refresh/TokenRefresher.spec.ts, packages/node/src/login/oidc/refresh/TokenRefresher.ts
This fixes #1767.
When using a Client Identifier as defined in Solid-OIDC, a client does not have a secret. Based on https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1, it looks like it is acceptable to only provide a client id, but no secret, in the authentication information stored in the body of the request to the token endpoint.
However, this is currently running into an issue with the underlying OIDC library. A conversation is happening at https://github.com/panva/node-openid-client/discussions/430. In the meantime, an arbitrary secret is given to the library, which works around the issue and is ignored by the server.
=> Fix authn when using client identifiers

CHANGELOG.md, lerna.json, packages/browser/package-lock.json, packages/browser/package.json, packages/core/package-lock.json, packages/core/package.json, packages/node/package-lock.json, packages/node/package.json, packages/oidc/package-lock.json, packages/oidc/package.json
This PR bumps the version to 1.11.3.
=> v1.11.3 release

package-lock.json, package.json, playwright.shared.config.ts
* Pins `@playwright/test` to `~1.37.0`
* Re-enables WebKit tests
=> SDK-3286: Pin playwright and re-enable WebKit tests

CHANGELOG.md, e2e/node/server/e2e-app-test.spec.ts, e2e/node/server/express.ts, package.json, packages/browser/src/ClientAuthentication.spec.ts, packages/browser/src/ClientAuthentication.ts, packages/browser/src/Session.ts, packages/core/src/Session.ts, packages/core/src/SessionEventListener.ts, packages/core/src/authenticatedFetch/fetchFactory.ts, packages/core/src/index.ts, packages/core/src/login/ILoginOptions.ts, packages/core/src/login/oidc/IIncomingRedirectHandler.ts, packages/core/src/login/oidc/IOidcOptions.ts, packages/core/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts, packages/core/src/sessionInfo/ISessionInfo.ts, packages/core/src/storage/StorageUtility.spec.ts, packages/core/src/storage/StorageUtility.ts, packages/node/examples/multiSession/src/serverSideApp.mjs, packages/node/src/ClientAuthentication.spec.ts, packages/node/src/ClientAuthentication.ts, packages/node/src/Session.ts, packages/node/src/login/oidc/AggregateIncomingRedirectHandler.ts, packages/node/src/login/oidc/OidcLoginHandler.spec.ts, packages/node/src/login/oidc/OidcLoginHandler.ts, packages/node/src/login/oidc/incomingRedirectHandler/AuthCodeRedirectHandler.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.ts, packages/node/src/multiSession.ts, packages/node/src/sessionInfo/SessionInfoManager.ts
In a server-side scenario, one may not want sessions to proactively refresh to keep their access token active. Instead, the session si logged in using the refresh token when loaded from storage, but it will only be active during the lifetime of its Access Token.
When building a Session, a new option "keepAlive" is supported. It defaults to 'true' for backwards compatibility. If set to 'false', the refresh token of the session will not be used to proactively refresh the access token. `keepAlive` is persisted in storage with the session state so that it is used after the authorization request during the token request in the authorization code flow.
The default value is set in multiple places, which is a bad thing. This can be fixed later.
=> Allow to disable session background refresh

packages/core/src/authenticatedFetch/dpopUtils.ts, packages/core/src/authenticatedFetch/fetchFactory.ts, tsconfig.build.json
This PR fixes issues on .md files generation due to deprecated typedoc options.
=> Fix typedoc generation

tsconfig.build.json
Changing back `"excludeNotDocumented": true`  to `"excludeNotDocumented": false` in the `/tsconfig.build.json`  file.  Otherwise, the ILoginInputOptions, IEndSessionOptions.html, IHasSessionEventListener, IHandleIncomingRedirectOptions, ISessionEventListener, ISessionOptions pages aren't generated.
=> update tsdoc config to include not documented

CHANGELOG.md, packages/browser/src/login/oidc/refresh/TokenRefresher.spec.ts, packages/browser/src/login/oidc/refresh/TokenRefresher.ts
The local storage is not a secure storage, and as such the refresh token should not be stored there. This issue is mitigated by the token being DPoP-bound, and the DPoP key not being available in storage.
This PR fixes bug #3518 .
=> 3518: Do not store refresh token in local storage

CHANGELOG.md, packages/node/src/login/oidc/__mocks__/IOidcOptions.ts, packages/node/src/login/oidc/oidcHandlers/ClientCredentialsOidcHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/ClientCredentialsOidcHandler.ts
When logging in using the Client Credentials flow, the `keepAlive` option set on the Session should be enforced.
=> SDK-3349: keepAlive option in client cred. flow

CHANGELOG.md, packages/browser/src/ClientAuthentication.ts, packages/browser/src/Session.ts, packages/node/src/ClientAuthentication.ts, packages/node/src/Session.spec.ts, packages/node/src/Session.ts, packages/node/src/multiSession.spec.ts
This PR fixes bug `clientAppId` not being added in `ISessionInfo` object.
=> Adding `clientAppId` to `ISessionInfo` object

.github/dependabot.yml
The major version upgrades to the eslint and typedoc-plugin-markdown dependencies require some more significant refactors of the existing code. For now, these updates will be turned off to produce less dependabot noise.
=> Ignore major updates to eslint and typedoc

packages/node/src/login/oidc/ClientRegistrar.spec.ts, packages/node/src/login/oidc/OidcLoginHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/ClientCredentialsOidcHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.spec.ts
This removes some additional hard-coded secrets from the test code that were missed in #3631
=> Remove additional hardcoded secrets from test code

packages/browser/package.json, packages/core/package.json, packages/node/package.json, packages/oidc-browser/package.json
As of 2024-09-18, a change in NPM (?) results in `npm view @inrupt/solid-client-authn repository.url` not showing the `git+...` URL of the repo, but shows `https://...` instead. This is an attempt at making this command consistent accross all of our repositories.
=> Align repository URLs with other libraries

CHANGELOG.md, packages/core/src/logout/endSessionUrl.ts, packages/node/examples/multiSession/src/serverSideApp.mjs, packages/node/src/ClientAuthentication.ts, packages/node/src/login/oidc/__mocks__/IOidcOptions.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.spec.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.ts
The IdP logout no longer fails in Node if the session was restored from storage (using `getSessionFromStorage`), which is the typical use case of how the session should be retrieved.
=> Fix IdP logout in node

CHANGELOG.md, packages/core/src/SessionEventListener.ts
Reapplies #3750 for CI
There are some scenarios where an Error is thrown rather than a string, for example within ClientAuthentication.
=> Improve SessionEventListener types

LICENSE, jest.setup.ts, packages/browser/examples/single/bundle/src/App.js, packages/browser/examples/single/bundle/src/index.js, packages/browser/examples/single/bundle/webpack.config.js, packages/node/examples/demoClientApp/src/index.js, packages/node/examples/multiSession/src/serverSideApp.mjs
Fixes #3841.
The browser demo no longer passes an incorrect argument (from a TS perspective) to the `handleIncomingRedirect` function. This also fixes how the React app root is created with respect to the latest upgrade.
=> Fix browser demo error management

CHANGELOG.md, package-lock.json, packages/core/src/sessionInfo/ISessionInfo.ts, packages/node/examples/multiSession/.env.example, packages/node/examples/multiSession/package.json, packages/node/examples/multiSession/src/serverSideApp.mjs, packages/node/src/Session.ts, packages/node/src/index.ts, packages/node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.ts, packages/node/src/multiSession.ts, packages/node/src/sessionInfo/SessionInfoManager.ts
This adds a function to the `multisession` module to be able to refresh
a `SessionTokenSet`. It also fixes the internal session info to keep
track of the DPoP keys.
- [] Relevant documentation, if any, has been written/updated.
=> Refresh tokens in NodeJS

packages/node/src/Session.ts
In the case of a session built from `Session.fromTokens` being used inside of `refreshTokens`, the default behavior of the session automatically rotating the refresh tokens was not disabled.
=> Prevent automatic refresh of the session

packages/node/src/multiSession.fromTokens.spec.ts, packages/node/src/multiSession.spec.ts, packages/node/src/multiSession.ts, packages/node/src/multisession.fromTokens.ts
Split the Session manipulation functions between the legacy ones using the embedded storage and the new ones integrated with external storage.
This is just some code moving around, it has no effect on the public API.
=> Internal refactoring of multisession functions

e2e/browser/solid-client-authn-browser/test-app/components/authenticatedFetch/index.tsx, packages/node/src/index.ts, packages/node/src/multiSession.fromTokens.spec.ts, packages/node/src/multiSession.spec.ts, packages/node/src/multiSession.ts, packages/node/src/multisession.fromTokens.ts
In some cases, a stale value was read from the application UI wile it was being re-rendered. This change makes it so that the test-id being rendered is removed from the DOM while the data is being fetched so that the test script waits for the latest value to be displayed.
=> Fix race condition in browser-based test

CHANGELOG.md, e2e/node/server/e2e-app-test.spec.ts, e2e/node/server/express.ts, packages/node/src/Session.ts, packages/node/src/index.ts, packages/node/src/multiSession.fromTokens.spec.ts, packages/node/src/multisession.fromTokens.ts
This adds a `logout` function to the mutlisession module so that server-side applications managing the tokens in an external storage can easily log the user out of their OpenID Provider.
=> Multisession RP-initiated logout

packages/node/examples/server/src/serverSideApp.mjs
An await was missing when calling `Session.fromAuthorizationRequestState`
=> Fix fromAuthorizationRequestState example

.github/workflows/ci.yml
The `sonarcloud-github-action` is deprecated in favor of `sonarqube-scan-action`
=> Update Sonar CI workflow
